<?php
require __DIR__.'/bootstrap.php';require __DIR__.'/bootstrap_auth.php';require_login();require_super_admin();
$roles=['super_admin','admin','manager','staff'];
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();try{$a=$_POST['action']??'';
if($a==='create'){ $name=trim($_POST['name']??'');$u=trim($_POST['username']??'');$pw=$_POST['password']??'';$role=in_array($_POST['role']??'', $roles,true)?$_POST['role']:'staff';if(!$name||!$u||strlen($pw)<8)throw new Exception('Name, username and password (8+ chars) are required.');$q=db()->prepare("INSERT INTO admins(username,password_hash,name,role,is_active) VALUES(?,?,?,?,1)");$q->execute([$u,password_hash($pw,PASSWORD_DEFAULT),$name,$role]);audit('CREATE_ADMIN','admin',(int)db()->lastInsertId(),$role);flash('success','Admin user created.');
}elseif($a==='role'){ $id=(int)$_POST['id'];$role=$_POST['role']??'staff';if(!in_array($role,$roles,true))throw new Exception('Invalid role.');if($id===(int)$_SESSION['admin_id']&&$role!=='super_admin')throw new Exception('You cannot remove your own Super Admin role.');db()->prepare("UPDATE admins SET role=? WHERE id=?")->execute([$role,$id]);audit('CHANGE_ADMIN_ROLE','admin',$id,$role);flash('success','Role updated.');
}elseif($a==='toggle'){ $id=(int)$_POST['id'];if($id===(int)$_SESSION['admin_id'])throw new Exception('You cannot disable your own account.');db()->prepare("UPDATE admins SET is_active=1-is_active WHERE id=?")->execute([$id]);audit('TOGGLE_ADMIN','admin',$id);flash('success','Account status updated.');}
}catch(Throwable $e){flash('danger',$e->getMessage());}redirect('admin_users.php');}
$rows=db()->query("SELECT id,username,name,role,is_active FROM admins ORDER BY id")->fetchAll();
?><!doctype html><html><head><?php include __DIR__.'/partials/head.php';?></head><body><?php include __DIR__.'/partials/nav.php';?><main class="wrap"><?php flash_render();?>
<section class="card"><div class="head"><div><div class="eyebrow">ACCESS CONTROL</div><h2>Admin Users</h2><p class="muted">Super Admin only.</p></div></div>
<form method="post" class="formgrid"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="create"><label>Name<input name="name" required></label><label>Username<input name="username" required></label><label>Password<input type="password" name="password" minlength="8" required></label><label>Role<select name="role"><?php foreach($roles as $r):?><option value="<?=$r?>"><?=$r?></option><?php endforeach;?></select></label><button class="btn primary">+ Add User</button></form></section>
<section class="card"><h2>Existing Users</h2><div class="table-wrap responsive-table"><table><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<?php foreach($rows as $a):?><tr><td><b><?=h($a['name'])?></b></td><td><?=h($a['username'])?></td><td><form method="post" style="display:flex;gap:6px"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="role"><input type="hidden" name="id" value="<?=$a['id']?>"><select name="role"><?php foreach($roles as $r):?><option value="<?=$r?>" <?=$a['role']===$r?'selected':''?>><?=$r?></option><?php endforeach;?></select><button class="btn secondary">Save</button></form></td><td><?=$a['is_active']?'Active':'Disabled'?></td><td><?php if((int)$a['id']!==(int)$_SESSION['admin_id']):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$a['id']?>"><button class="btn <?=$a['is_active']?'danger':'primary'?>"><?=$a['is_active']?'Disable':'Enable'?></button></form><?php endif;?></td></tr><?php endforeach;?>
</tbody></table></div></section></main></body></html>