<?php require __DIR__.'/bootstrap.php';require __DIR__.'/room_inventory.php';require_login();$tid=require_tour();$t=tour_row($tid);$roomInventory=gmjs_room_inventory($tid);
$q=db()->prepare("SELECT b.*,(SELECT COUNT(*) FROM passengers p WHERE p.bus_id=b.id AND p.status='ACTIVE') booked FROM buses b WHERE b.tour_id=? AND b.active=1 ORDER BY b.id");$q->execute([$tid]);$buses=$q->fetchAll();
$passq=db()->prepare("SELECT p.*,b.name bus_name,s.seat_no FROM passengers p JOIN buses b ON b.id=p.bus_id JOIN seats s ON s.id=p.seat_id WHERE p.tour_id=? AND p.status='ACTIVE' ORDER BY b.id,s.row_no,s.col_no");$passq->execute([$tid]);$passengers=$passq->fetchAll();
$payq=db()->prepare("SELECT p.id,COALESCE(SUM(pay.amount),0) paid FROM passengers p LEFT JOIN payments pay ON pay.passenger_id=p.id WHERE p.tour_id=? GROUP BY p.id");$payq->execute([$tid]);$paidMap=[];foreach($payq as $x)$paidMap[$x['id']]=(float)$x['paid'];
$payments=(float)($dbpay=$dbpay??0);$q=$dbpayq=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM payments pay JOIN passengers p ON p.id=pay.passenger_id WHERE p.tour_id=?");$q->execute([$tid]);$payments=(float)$q->fetchColumn();
$q=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM expenses WHERE tour_id=?");$q->execute([$tid]);$expenses=(float)$q->fetchColumn();
$q=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM incomes WHERE tour_id=?");$q->execute([$tid]);$otherIncome=(float)$q->fetchColumn();
$totalIncome=$payments+$otherIncome;
$balance=$totalIncome-$expenses;
$totalSeats=array_sum(array_map(fn($b)=>(int)$b['seat_count'],$buses));$booked=count($passengers);$due=0;foreach($passengers as $p)$due+=max(0,(float)$p['final_fee']-($paidMap[$p['id']]??0));
?><!doctype html><html><head><meta name="csrf-token" content="<?=h(csrf())?>"><?php include __DIR__.'/partials/head.php';?></head><body><?php include __DIR__.'/partials/nav.php';?><main class="wrap"><?php flash_render();?>
<div class="stats"><div class="stat"><span>Booked</span><b><?=$booked?>/<?=$totalSeats?></b></div><div class="stat"><span>Available</span><b><?=$totalSeats-$booked?></b></div><div class="stat"><span>Total Collection</span><b><?=money($payments+$due)?></b></div><div class="stat"><span>Ticket Collection</span><b><?=money($payments)?></b></div><div class="stat"><span>Other Income</span><b><?=money($otherIncome)?></b></div><div class="stat"><span>Due</span><b><?=money($due)?></b></div><div class="stat"><span>Expense</span><b><?=money($expenses)?></b></div><div class="stat"><span>Net Balance</span><b><?=money($balance)?></b></div></div>
<section class="card"><div class="head"><div><div class="eyebrow">ROOM INVENTORY</div><h2>Room Availability</h2><p class="muted">Total rooms, available rooms and booking capacity.</p></div><a class="btn secondary" href="rooms.php">Manage Rooms</a></div><div class="grid2"><?php foreach($roomInventory as $ri):?><div class="stat"><span><?=h($ri['label'])?></span><b><?=$ri['available_rooms']?> / <?=$ri['rooms']?> rooms available</b><small class="muted"><?=$ri['available_beds']?> / <?=$ri['beds']?> booking slots available · <?=$ri['used_beds']?> booked</small><?php if($ri['full']):?><div class="badge due">FULL</div><?php endif;?></div><?php endforeach;?></div></section><section class="card"><div class="head"><div><div class="eyebrow">SEAT BOOKING</div><h2>Bus Seats</h2></div><div class="row-actions"><a class="btn secondary" href="summary_print.php?tour_id=<?=$tid?>">Print Summary</a><a class="btn secondary" href="passenger_print.php?tour_id=<?=$tid?>">Print List</a><a class="btn primary" href="passenger_form.php">+ Passenger</a></div></div><div class="bus-tabs"><?php foreach($buses as $i=>$b):?><button class="bus-tab <?=$i===0?'active':''?>" data-bus="<?=$b['id']?>"><?=h($b['name'])?> <small><?=$b['booked']?>/<?=$b['seat_count']?></small></button><?php endforeach;?></div><div class="legend"><span><i class="dot green"></i> Available</span><span><i class="dot red"></i> Booked</span><span><i class="dot orange"></i> Payment Due</span></div><div id="seatDragHint" class="muted" style="margin:10px 0 0;padding:10px 12px;background:#f8fafc;border-radius:10px;font-size:12px"></div><div id="seatMap" class="seat-map"></div></section>
<section class="card"><div class="head"><h2>Passenger List</h2><a class="btn primary" href="passengers.php">View Full List</a></div><input id="search" placeholder="Search name, phone, seat..."><div class="table-wrap responsive-table" style="margin-top:12px"><table><thead><tr><th>Seat</th><th>Name</th><th>Phone</th><th>Room</th><th>Fee</th><th>Paid</th><th>Due</th><th></th></tr></thead><tbody id="passengerRows"></tbody></table></div></section>
</main><div id="toast" class="toast"></div><script>const PASSENGERS=<?=json_encode($passengers)?>,PAID_MAP=<?=json_encode($paidMap)?>,BUSES=<?=json_encode($buses)?>;</script><script src="assets/dashboard.js"></script></body></html>
