<?php
declare(strict_types=1);
require __DIR__.'/bootstrap_saas.php';
if (saas_authenticated()) {
    $orgs = saas_organizations_for_user(saas_user_id());
    if ($orgs) saas_redirect('saas_dashboard.php');
    saas_redirect('organization_create.php');
}
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GoTM — Tour Management Software for Modern Tour Operators</title>
<meta name="description" content="GoTM is an all-in-one tour management platform for tour operators, travel groups and bus tours. Manage passengers, seats, rooms, payments, tickets, teams and public bookings in one place.">
<meta name="theme-color" content="#0B2A49">
<link rel="icon" href="assets/gotm-logo.png">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet">
<style>
:root{--navy:#0b2a49;--navy2:#123b60;--gold:#f7ab17;--gold2:#ffca4b;--ink:#10263b;--muted:#65788b;--bg:#f7fafc;--line:#e4ebf1;--white:#fff;--green:#0f8b55;--shadow:0 24px 70px rgba(11,42,73,.12)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:"DM Sans",system-ui,sans-serif;color:var(--ink);background:var(--white)}a{text-decoration:none;color:inherit}.container{width:min(1160px,calc(100% - 40px));margin:auto}
.nav{height:76px;display:flex;align-items:center;justify-content:space-between;gap:24px}.nav-logo img{height:46px;width:auto;display:block}.nav-links{display:flex;gap:28px;align-items:center;font-size:14px;font-weight:600;color:#52677b}.nav-links a:hover{color:var(--navy)}.nav-actions{display:flex;gap:10px;align-items:center}.btn{display:inline-flex;align-items:center;justify-content:center;border-radius:10px;padding:12px 18px;font-weight:800;font-size:14px;transition:.2s}.btn:hover{transform:translateY(-2px)}.btn-outline{border:1px solid #d4dfe8}.btn-primary{background:var(--gold);color:var(--navy);box-shadow:0 9px 25px rgba(247,171,23,.25)}.btn-dark{background:var(--navy);color:#fff}.menu{display:none;border:0;background:transparent;font-size:26px}
.hero{background:radial-gradient(circle at 85% 15%,#fff3cc 0,transparent 28%),linear-gradient(180deg,#f8fbfe 0,#fff 100%);padding:76px 0 70px;overflow:hidden}.hero-grid{display:grid;grid-template-columns:1.02fr .98fr;gap:55px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:7px 11px;border-radius:999px;background:#fff6dc;color:#9a6500;font-size:12px;font-weight:800;border:1px solid #f8df9e}.eyebrow i{width:7px;height:7px;border-radius:50%;background:var(--gold);display:block}.hero h1{font-family:Manrope,sans-serif;font-size:clamp(42px,5.2vw,68px);line-height:1.02;letter-spacing:-2.8px;margin:18px 0}.hero h1 span{color:var(--navy)}.hero h1 em{font-style:normal;color:#d99000}.hero p{font-size:19px;line-height:1.65;color:var(--muted);max-width:650px;margin:0 0 28px}.hero-actions{display:flex;gap:12px;flex-wrap:wrap}.hero-note{display:flex;gap:20px;margin-top:22px;color:#718294;font-size:12px}.hero-note span:before{content:"✓";color:var(--green);font-weight:900;margin-right:6px}
.dashboard{position:relative}.dashboard-card{background:#fff;border:1px solid #e0e8ef;border-radius:22px;box-shadow:var(--shadow);overflow:hidden;transform:rotate(1deg)}.dash-top{background:var(--navy);padding:15px 18px;color:#fff;display:flex;justify-content:space-between}.dash-top strong{font-size:12px}.dash-body{padding:18px}.dash-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.mini{border:1px solid var(--line);border-radius:12px;padding:12px}.mini small{color:#778899}.mini b{display:block;font-size:21px;margin-top:4px}.chart{height:155px;border-radius:14px;background:linear-gradient(180deg,#fffdf7,#fff);border:1px solid var(--line);margin-top:12px;padding:18px;position:relative}.chart svg{width:100%;height:100%}.dash-list{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;margin-top:12px}.listbox{border:1px solid var(--line);border-radius:12px;padding:12px}.listrow{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #edf1f4;font-size:11px}.listrow:last-child{border:0}.pill{border-radius:99px;padding:4px 7px;background:#eaf8ef;color:#15814f;font-weight:800}.floating{position:absolute;right:-28px;bottom:28px;background:#fff;border:1px solid var(--line);box-shadow:0 18px 40px rgba(11,42,73,.14);border-radius:15px;padding:14px 16px;width:180px}.floating strong{display:block;font-size:12px}.floating span{font-size:11px;color:var(--muted)}
.trust{padding:25px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.trust-row{display:flex;justify-content:center;gap:40px;flex-wrap:wrap;color:#8090a0;font-size:12px;font-weight:800;letter-spacing:.4px}
.section{padding:95px 0}.section.alt{background:var(--bg)}.section-head{text-align:center;max-width:760px;margin:0 auto 48px}.section-kicker{color:#bd7b00;font-weight:900;font-size:12px;letter-spacing:1.4px;text-transform:uppercase}.section h2{font-family:Manrope,sans-serif;font-size:clamp(32px,4vw,48px);letter-spacing:-1.8px;line-height:1.1;margin:10px 0 14px}.section-head p{font-size:17px;line-height:1.65;color:var(--muted);margin:0}
.features{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.feature{padding:25px;border:1px solid var(--line);border-radius:18px;background:#fff;transition:.2s}.feature:hover{transform:translateY(-4px);box-shadow:var(--shadow)}.icon{width:44px;height:44px;border-radius:12px;background:#fff4d6;color:#9b6700;display:grid;place-items:center;font-size:21px;margin-bottom:17px}.feature h3{font-size:18px;margin:0 0 8px}.feature p{font-size:14px;line-height:1.65;color:var(--muted);margin:0}
.workflow{display:grid;grid-template-columns:repeat(4,1fr);gap:0}.step{padding:24px;border-top:2px solid var(--navy);position:relative}.step:not(:last-child):after{content:"→";position:absolute;right:-9px;top:-15px;background:#fff;color:var(--gold);font-size:25px}.num{font-size:12px;color:#b27400;font-weight:900}.step h3{margin:10px 0 7px}.step p{font-size:13px;color:var(--muted);line-height:1.55}
.split{display:grid;grid-template-columns:1fr 1fr;gap:65px;align-items:center}.visual{border-radius:24px;background:linear-gradient(145deg,var(--navy),#194a72);padding:28px;box-shadow:var(--shadow);color:#fff}.visual-window{background:#f9fbfd;color:var(--ink);border-radius:16px;padding:16px}.visual-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.seatgrid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.seat{height:38px;border-radius:7px;background:#eaf8ef;border:1px solid #b9e6c9}.seat.booked{background:#ffe6e9;border-color:#f6b2bc}.room{margin-top:14px;border:1px solid #e4ebf1;border-radius:11px;padding:11px;font-size:11px}.checkline{display:flex;gap:8px;align-items:center;margin:11px 0;font-size:13px}.checkline b{color:var(--green)}.copy h2{margin-top:0}.copy p{color:var(--muted);line-height:1.7}.copy ul{padding:0;list-style:none}.copy li{padding:8px 0;font-size:14px}.copy li:before{content:"✓";font-weight:900;color:var(--green);margin-right:9px}
.pricing{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.price-card{border:1px solid var(--line);border-radius:18px;padding:24px;background:#fff}.price-card.featured{border:2px solid var(--gold);box-shadow:0 18px 45px rgba(247,171,23,.14);transform:translateY(-7px)}.price-card .tag{display:inline-block;background:#fff4d6;color:#9a6500;padding:5px 8px;border-radius:99px;font-size:10px;font-weight:900}.price-card h3{margin:16px 0 4px}.price{font-family:Manrope;font-size:28px;font-weight:800}.price small{font:12px "DM Sans";color:var(--muted)}.price-card p{font-size:12px;color:var(--muted);min-height:38px}.price-card ul{padding:0;list-style:none;font-size:12px;color:#536678;line-height:2}.price-card li:before{content:"✓";color:var(--green);margin-right:7px;font-weight:900}
.cta{padding:75px 0}.cta-box{background:linear-gradient(135deg,var(--navy),#174d78);border-radius:28px;padding:55px;display:flex;justify-content:space-between;gap:30px;align-items:center;color:#fff;overflow:hidden;position:relative}.cta-box:after{content:"";position:absolute;width:300px;height:300px;border-radius:50%;background:#f7ab1720;right:-80px;top:-120px}.cta-box h2{font-family:Manrope;font-size:42px;letter-spacing:-1.5px;margin:0 0 10px}.cta-box p{color:#c8d8e7;margin:0;max-width:650px}.footer{background:#071d32;color:#afc0cf;padding:50px 0 25px}.footer-grid{display:grid;grid-template-columns:1.5fr repeat(3,1fr);gap:30px}.footer-logo img{height:40px;filter:brightness(0) invert(1);margin-bottom:12px}.footer h4{color:#fff;margin:0 0 12px}.footer a{display:block;font-size:12px;padding:5px 0}.footer-bottom{border-top:1px solid #ffffff15;margin-top:30px;padding-top:18px;font-size:11px;display:flex;justify-content:space-between}
@media(max-width:950px){.nav-links{display:none}.menu{display:block}.hero-grid,.split{grid-template-columns:1fr}.hero{padding-top:50px}.features{grid-template-columns:1fr 1fr}.pricing{grid-template-columns:1fr 1fr}.workflow{grid-template-columns:1fr 1fr}.step:nth-child(2):after{display:none}.footer-grid{grid-template-columns:2fr 1fr 1fr}}
@media(max-width:600px){.container{width:min(100% - 28px,1160px)}.nav{height:68px}.nav-logo img{height:39px}.nav-actions .btn-outline{display:none}.hero h1{letter-spacing:-1.8px}.hero p{font-size:16px}.hero-note{flex-direction:column;gap:7px}.features,.pricing,.workflow{grid-template-columns:1fr}.step:not(:last-child):after{display:none}.section{padding:70px 0}.dashboard-card{transform:none}.floating{position:static;margin:12px auto 0}.dash-list{grid-template-columns:1fr}.cta-box{padding:34px 25px;display:block}.cta-box h2{font-size:32px;margin-bottom:14px}.cta-box .btn{margin-top:22px}.footer-grid{grid-template-columns:1fr 1fr}.footer-grid>div:first-child{grid-column:1/-1}.footer-bottom{display:block}.footer-bottom span{display:block;margin-top:6px}}
</style>
</head>
<body>
<header><div class="container nav">
<a class="nav-logo" href="/"><img src="assets/gotm-logo.png" alt="GoTM — GoZyraa Tour Management"></a>
<nav class="nav-links"><a href="#features">Features</a><a href="#how">How it works</a><a href="#operations">Operations</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav>
<div class="nav-actions"><a class="btn btn-outline" href="saas_login.php">Sign in</a><a class="btn btn-primary" href="saas_login.php">Start free</a></div><button class="menu" aria-label="Menu">☰</button>
</div></header>
<main>
<section class="hero"><div class="container hero-grid"><div>
<span class="eyebrow"><i></i> ALL-IN-ONE TOUR MANAGEMENT</span>
<h1>Run every tour from <span>one powerful</span> <em>platform.</em></h1>
<p>GoTM brings bookings, passengers, buses, seats, rooms, payments, tickets, teams and public registration together — so your team can spend less time managing spreadsheets and more time running great tours.</p>
<div class="hero-actions"><a class="btn btn-primary" href="saas_login.php">Start free — no card required</a><a class="btn btn-outline" href="#features">Explore features ↓</a></div>
<div class="hero-note"><span>Secure multi-organization setup</span><span>Public booking pages</span><span>Built for growing tour operators</span></div>
</div>
<div class="dashboard"><div class="dashboard-card"><div class="dash-top"><strong>GoTM Dashboard</strong><span>Live tour overview</span></div><div class="dash-body"><div class="dash-stats"><div class="mini"><small>Passengers</small><b>128</b></div><div class="mini"><small>Paid</small><b>৳ 4.82L</b></div><div class="mini"><small>Seats</small><b>92%</b></div></div><div class="chart"><svg viewBox="0 0 500 150" preserveAspectRatio="none"><path d="M0 125 C60 110 75 95 120 105 S180 70 225 82 S280 45 325 64 S385 35 430 47 S470 20 500 28" fill="none" stroke="#F7AB17" stroke-width="5" stroke-linecap="round"/><path d="M0 150 L0 125 C60 110 75 95 120 105 S180 70 225 82 S280 45 325 64 S385 35 430 47 S470 20 500 28 L500 150 Z" fill="#F7AB1712"/></svg></div><div class="dash-list"><div class="listbox"><b style="font-size:12px">Upcoming tours</b><div class="listrow"><span>Kuakata Escape</span><span class="pill">64 seats</span></div><div class="listrow"><span>Sylhet Weekend</span><span class="pill">42 seats</span></div><div class="listrow"><span>Cox's Bazar</span><span class="pill">22 seats</span></div></div><div class="listbox"><b style="font-size:12px">Payments</b><div class="listrow"><span>Paid</span><b>৳ 4.82L</b></div><div class="listrow"><span>Due</span><b style="color:#c17b00">৳ 1.14L</b></div><div class="listrow"><span>Requests</span><b>8</b></div></div></div></div></div><div class="floating"><strong>✓ Ticket issued</strong><span>Passenger #GTM-24081 · QR ready</span></div></div></div></section>
<section class="trust"><div class="container trust-row"><span>TOURS</span><span>GROUP TRAVEL</span><span>BUS OPERATORS</span><span>TRAVEL TEAMS</span><span>EVENT TOURS</span></div></section>
<section class="section" id="features"><div class="container"><div class="section-head"><div class="section-kicker">Everything in one place</div><h2>All the tools your tour operation needs.</h2><p>From the first registration to the final ticket, GoTM connects the workflow your team already manages every day.</p></div><div class="features">
<article class="feature"><div class="icon">◈</div><h3>Tour & organization management</h3><p>Create organizations and tours with clean tenant and tour isolation. Manage managers, admins and staff with role-based access.</p></article><article class="feature"><div class="icon">◉</div><h3>Public booking pages</h3><p>Give every tour a shareable public page where passengers can register, log in and manage their booking.</p></article><article class="feature"><div class="icon">▦</div><h3>Passenger management</h3><p>Create new passengers or reuse organization profiles from previous tours — without carrying old booking state.</p></article><article class="feature"><div class="icon">⌂</div><h3>Bus & seat management</h3><p>Set up buses, visual seat plans and secure seat selection. Keep availability accurate while your team operates.</p></article><article class="feature"><div class="icon">□</div><h3>Room management</h3><p>Create rooms, capacity and allocations. Let passengers choose available rooms through the booking portal.</p></article><article class="feature"><div class="icon">৳</div><h3>Payments & payment requests</h3><p>Track fees, discounts, feature charges, payment intents, received payments, balances and payment status.</p></article><article class="feature"><div class="icon">✓</div><h3>Automatic tickets & QR</h3><p>Issue branded digital tickets automatically after full payment with secure QR verification.</p></article><article class="feature"><div class="icon">✦</div><h3>Tour features</h3><p>Enable food, T-shirt size, train ticket, launch ticket and future custom features per tour.</p></article><article class="feature"><div class="icon">◫</div><h3>Team & permissions</h3><p>Manage organization members and assign tour-level roles so every person sees and controls only what they need.</p></article><article class="feature"><div class="icon">▤</div><h3>Reports & operations</h3><p>See passengers, revenue, expenses, balances and tour activity from a centralized operational dashboard.</p></article><article class="feature"><div class="icon">◎</div><h3>Customer self-service</h3><p>Passengers can select seats, rooms, extras, make payment requests and access their tickets without calling your team.</p></article><article class="feature"><div class="icon">⚿</div><h3>Security & audit</h3><p>Tenant isolation, CSRF protection, rate limiting, audit logs, secure sessions and payment idempotency built into the platform.</p></article>
</div></div></section>
<section class="section alt" id="how"><div class="container"><div class="section-head"><div class="section-kicker">Simple workflow</div><h2>From tour idea to ticket in a few steps.</h2><p>GoTM keeps your operations connected from setup through departure.</p></div><div class="workflow"><div class="step"><div class="num">01 — CREATE</div><h3>Create your tour</h3><p>Set dates, fee, public page, buses, rooms and the features your tour needs.</p></div><div class="step"><div class="num">02 — PUBLISH</div><h3>Share the booking link</h3><p>Publish a beautiful tour page and let passengers register from any device.</p></div><div class="step"><div class="num">03 — MANAGE</div><h3>Run the operation</h3><p>Manage passengers, seats, rooms, payments, team members and tour activity in one dashboard.</p></div><div class="step"><div class="num">04 — ISSUE</div><h3>Deliver tickets</h3><p>Once a passenger is fully paid, GoTM can issue the secure digital ticket and QR.</p></div></div></div></section>
<section class="section" id="operations"><div class="container split"><div class="visual"><div style="font-size:12px;opacity:.75;margin-bottom:10px">LIVE TOUR • SEAT & ROOM ALLOCATION</div><div class="visual-window"><div class="visual-head"><strong>Kuakata Escape</strong><span class="pill">92% booked</span></div><div class="seatgrid"><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat booked"></div><div class="seat "></div><div class="seat "></div><div class="seat "></div><div class="seat "></div><div class="seat "></div><div class="seat "></div><div class="seat "></div></div><div class="room"><b>Room 304</b><br><span style="color:#6b7d8d">3 / 4 guests assigned · 1 space available</span></div><div class="checkline"><b>✓</b> Passenger payment confirmed</div><div class="checkline"><b>✓</b> Ticket QR issued automatically</div></div></div><div class="copy"><div class="section-kicker">Built for real tour operations</div><h2>One source of truth for your whole team.</h2><p>Stop switching between Messenger, spreadsheets, payment notes and separate passenger lists. GoTM connects the information that matters to the same tour and organization.</p><ul><li>Live passenger, seat and room status</li><li>Tour-level team access and permissions</li><li>Reusable customer profiles across tours</li><li>Secure payment and ticket lifecycle</li><li>Responsive customer self-service portal</li></ul></div></div></section>
<section class="section alt" id="pricing"><div class="container"><div class="section-head"><div class="section-kicker">Plans that scale with you</div><h2>Start free. Grow when you need more.</h2><p>Use the core GoTM workflow for free, then unlock higher limits and advanced capabilities as your operation grows.</p></div><div class="pricing"><div class="price-card"><span class="tag">START</span><h3>Free</h3><div class="price">৳0 <small>/ month</small></div><p>For small teams getting started.</p><ul><li>Up to 3 tours</li><li>5 team members</li><li>100 passengers / tour</li><li>Core booking & operations</li></ul><a class="btn btn-outline" href="saas_login.php">Start free</a></div><div class="price-card featured"><span class="tag">MOST FLEXIBLE</span><h3>Pro</h3><div class="price">৳999 <small>/ month</small></div><p>For growing tour operators.</p><ul><li>Up to 50 tours</li><li>25 team members</li><li>1,000 passengers / tour</li><li>Custom branding & features</li></ul><a class="btn btn-primary" href="saas_login.php">Start with GoTM</a></div><div class="price-card"><span class="tag">GROWTH</span><h3>Business</h3><div class="price">৳2,499 <small>/ month</small></div><p>For larger operations and teams.</p><ul><li>Up to 500 tours</li><li>100 team members</li><li>5,000 passengers / tour</li><li>Advanced reporting</li></ul><a class="btn btn-outline" href="saas_login.php">Get started</a></div><div class="price-card"><span class="tag">SCALE</span><h3>Enterprise</h3><div class="price">Custom</div><p>For organizations with custom requirements.</p><ul><li>Unlimited core limits</li><li>Custom commercial terms</li><li>Advanced capabilities</li><li>Dedicated support path</li></ul><a class="btn btn-outline" href="#cta">Talk to us</a></div></div></div></section>
<section class="section" id="faq"><div class="container"><div class="section-head"><div class="section-kicker">FAQ</div><h2>Questions before you start?</h2></div><div class="features">
<article class="feature"><h3>Can I manage more than one tour?</h3><p>Yes. Your organization can manage multiple isolated tours, each with its own passengers, buses, rooms, payments, features and team assignments.</p></article>
<article class="feature"><h3>Can passengers book themselves?</h3><p>Yes. Each published tour can have a public booking page with passenger registration and a secure self-service booking portal.</p></article>
<article class="feature"><h3>Can I reuse old passengers?</h3><p>Yes. Organization-level passenger profiles can be reused while every new tour starts with fresh payment, seat, room and ticket state.</p></article>
<article class="feature"><h3>Does GoTM support teams?</h3><p>Yes. Organization members and tour-level roles let owners delegate operational work while keeping access scoped.</p></article>
<article class="feature"><h3>Can I customize the public tour page?</h3><p>Paid plans can unlock custom branding while the core public tour themes remain available for getting started.</p></article>
<article class="feature"><h3>Is payment gateway integration supported?</h3><p>GoTM's payment architecture is designed around payment intents and webhook-safe billing flows, allowing provider integrations to be added without changing the core booking lifecycle.</p></article>
</div></div></section>
<section class="cta" id="cta"><div class="container"><div class="cta-box"><div><div class="section-kicker" style="color:var(--gold2)">READY WHEN YOU ARE</div><h2>Make your next tour easier to run.</h2><p>Set up your GoTM workspace, create your first tour and start organizing your passengers, seats, rooms and payments in one place.</p></div><a class="btn btn-primary" href="saas_login.php">Start free →</a></div></div></section>
</main>
<footer class="footer"><div class="container footer-grid"><div><a class="footer-logo" href="/"><img src="assets/gotm-logo.png" alt="GoTM"></a><p style="font-size:12px;line-height:1.7;max-width:300px">GoTM — GoZyraa Tour Management. A modern platform for managing tours, bookings and passenger operations.</p></div><div><h4>Product</h4><a href="#features">Features</a><a href="#operations">Operations</a><a href="#pricing">Pricing</a></div><div><h4>Company</h4><a href="#how">How it works</a><a href="#faq">FAQ</a><a href="saas_login.php">Sign in</a></div><div><h4>Get started</h4><a href="saas_login.php">Start free</a><a href="#cta">Contact</a></div></div><div class="container footer-bottom"><span>© <?=date('Y')?> GoTM — GoZyraa Tour Management</span><span>Secure • Modern • Built for tour operators</span></div></footer>
<script>
document.querySelector('.menu')?.addEventListener('click',()=>{const n=document.querySelector('.nav-links');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='68px';n.style.left='14px';n.style.right='14px';n.style.padding='18px';n.style.background='#fff';n.style.border='1px solid #e4ebf1';n.style.borderRadius='14px';n.style.boxShadow='0 18px 45px rgba(11,42,73,.12)';n.style.flexDirection='column';n.style.alignItems='flex-start';});
</script>
</body></html>