<?php require __DIR__.'/bootstrap.php';require __DIR__.'/bootstrap_auth.php';require_login();$tid=require_tour();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$action=$_POST['action']??'';try{if($action==='delete'){require_permission('passenger.delete'); require_permission('passenger.delete'); $id=(int)$_POST['id'];$q=db()->prepare("UPDATE passengers SET status='CANCELLED' WHERE id=? AND tour_id=?");$q->execute([$id,$tid]);audit('DELETE_PASSENGER','passenger',$id);flash('success','Passenger cancelled and seat released.');}elseif($action==='restore'){ $id=(int)$_POST['id'];$q=db()->prepare("UPDATE passengers SET status='ACTIVE' WHERE id=? AND tour_id=?");$q->execute([$id,$tid]);flash('success','Passenger restored.');}}catch(Throwable $e){flash('danger',$e->getMessage());}redirect('passengers.php');}
$q=db()->prepare("SELECT p.*,b.name bus_name,s.seat_no,COALESCE((SELECT SUM(amount) FROM payments WHERE passenger_id=p.id),0) paid FROM passengers p JOIN buses b ON b.id=p.bus_id JOIN seats s ON s.id=p.seat_id WHERE p.tour_id=? AND p.status='ACTIVE' ORDER BY CASE WHEN p.departure IS NULL OR p.departure='' THEN 1 ELSE 0 END,p.departure,b.id,s.row_no,s.col_no");$q->execute([$tid]);$rows=$q->fetchAll();$q=$dbq=db()->prepare("SELECT COUNT(*) FROM passengers WHERE tour_id=? AND status='CANCELLED'");$q->execute([$tid]);$cancelled=(int)$q->fetchColumn();
$departureCounts=[];foreach($rows as $rp){$d=trim((string)($rp['departure']??''));$d=$d!==''?$d:'Not Set';$departureCounts[$d]=($departureCounts[$d]??0)+1;}
?><!doctype html><html><head><?php include __DIR__.'/partials/head.php';?></head><body><?php include __DIR__.'/partials/nav.php';?><main class="wrap"><?php flash_render();?><section class="card"><div class="head"><div><div class="eyebrow">PASSENGER MANAGEMENT</div><h2>Passenger List</h2><p class="muted">Filter passengers by their departure / pickup place before printing the boarding list.</p></div><div class="row-actions"><a id="printListBtn" class="btn secondary" href="passenger_print.php?tour_id=<?=$tid?>">Print List</a><button class="btn primary" onclick="printSelected()">Print Selected Tickets</button><a class="btn primary" href="passenger_form.php">+ Passenger</a></div></div>
<div class="formgrid" style="grid-template-columns:2fr 1fr;margin-bottom:14px"><label>Search<input id="search" placeholder="Search name, phone, seat, bus..."></label><label>Departure Place<select id="departureFilter"><option value="">All Departure Places</option><?php foreach($departureCounts as $d=>$cnt):?><option value="<?=h($d)?>"><?=h($d)?> — <?=$cnt?></option><?php endforeach;?></select></label></div>
<div id="filterSummary" class="alert" style="margin-bottom:12px">Showing all <?=count($rows)?> passengers.</div>
<div class="table-wrap responsive-table"><table id="passTable"><thead><tr><th><input type="checkbox" id="all"></th><th>Seat</th><th>Name</th><th>Phone</th><th>Departure</th><th>Bus</th><th>Room</th><th>Fee</th><th>Paid</th><th>Due</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $p):$due=max(0,(float)$p['final_fee']-(float)$p['paid']);$dep=trim((string)($p['departure']??''))?:'Not Set';?><tr data-departure="<?=h($dep)?>"><td data-label="Select"><input type="checkbox" class="ticket-check" value="<?=$p['id']?>"></td><td data-label="Seat"><?=h($p['seat_no'])?></td><td data-label="Name"><b><?=h($p['name'])?></b></td><td data-label="Phone"><?=h($p['phone'])?></td><td data-label="Departure"><b><?=h($dep)?></b></td><td data-label="Bus"><?=h($p['bus_name'])?></td><td data-label="Room"><?=h(room_label($p['room_type']))?></td><td data-label="Fee"><?=money($p['final_fee'])?></td><td data-label="Paid"><?=money($p['paid'])?></td><td data-label="Due"><?=$due?'<span class="badge due">'.money($due).'</span>':'<span class="badge">Paid</span>'?></td><td data-label="Actions"><a class="btn secondary" href="passenger_form.php?id=<?=$p['id']?>">Edit</a> <a class="btn primary" href="ticket.php?id=<?=$p['id']?>">Ticket</a> <form method="post" style="display:inline" onsubmit="return confirm('Cancel this passenger and release the seat?')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$p['id']?>"><?php if(can("passenger.delete")):?><button class="btn danger">Delete</button><?php endif;?></form></td></tr><?php endforeach;?></tbody></table></div></section></main><script>
const allBox=document.getElementById('all'), searchBox=document.getElementById('search'), depFilter=document.getElementById('departureFilter'), summary=document.getElementById('filterSummary'), printBtn=document.getElementById('printListBtn');
function applyFilters(){const q=(searchBox.value||'').toLowerCase().trim(), dep=depFilter.value;let visible=0;document.querySelectorAll('#passTable tbody tr').forEach(r=>{const text=r.innerText.toLowerCase(), rd=r.dataset.departure||'';const ok=(!q||text.includes(q))&&(!dep||rd===dep);r.style.display=ok?'':'none';if(ok)visible++;});summary.textContent=dep?`Showing ${visible} passenger${visible===1?'':'s'} from ${dep}.`:`Showing ${visible} passenger${visible===1?'':'s'} from all departure places.`;printBtn.href='passenger_print.php?tour_id=<?=$tid?>'+(dep?'&departure='+encodeURIComponent(dep):'');allBox.checked=false;}
allBox.onchange=e=>document.querySelectorAll('#passTable tbody tr').forEach(r=>{if(r.style.display!=='none'){const x=r.querySelector('.ticket-check');if(x)x.checked=e.target.checked;}});searchBox.oninput=applyFilters;depFilter.onchange=applyFilters;
function printSelected(){let ids=[...document.querySelectorAll('.ticket-check:checked')].map(x=>x.value);if(!ids.length)return alert('Select at least one passenger.');location.href='tickets.php?ids='+ids.join(',')}
</script></body></html>
