<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
require __DIR__.'/passenger_auth_helpers.php';
require __DIR__.'/passenger_auth_rate_limit.php';
$db=saas_db();$config=require __DIR__.'/config.php';
$appId=trim((string)(getenv('FACEBOOK_APP_ID')?:''));$appSecret=trim((string)(getenv('FACEBOOK_APP_SECRET')?:''));$baseUrl=rtrim((string)($config['app']['base_url']??''),'/');$redirectUri=$baseUrl.'/passenger_facebook_auth.php';
function fb_fail(string $message):never{http_response_code(400);echo '<!doctype html><html><body style="font-family:Arial;padding:40px"><h2>Facebook sign-in unavailable</h2><p>'.saas_h($message).'</p><p><a href="passenger_auth.php">Back to login</a></p></body></html>';exit;}
function fb_json(string $url,array $post=[]):array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>15,CURLOPT_HTTPHEADER=>['Accept: application/json']]);if($post){curl_setopt($ch,CURLOPT_POST,true);curl_setopt($ch,CURLOPT_POSTFIELDS,http_build_query($post));curl_setopt($ch,CURLOPT_HTTPHEADER,['Accept: application/json','Content-Type: application/x-www-form-urlencoded']);}$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($body===false||$status<200||$status>=300)throw new RuntimeException('Facebook authentication service could not be reached.'.($err?' '.$err:''));$data=json_decode((string)$body,true);if(!is_array($data))throw new RuntimeException('Invalid response from Facebook.');return $data;}
if($appId===''||$appSecret===''||$baseUrl==='')fb_fail('Facebook login is not configured. Set FACEBOOK_APP_ID, FACEBOOK_APP_SECRET and APP_BASE_URL on the server.');
if(passenger_oauth_rate_limited())fb_fail('Too many Facebook sign-in attempts. Please try again later.');
if(($_GET['action']??'')!=='callback'){
 $state=bin2hex(random_bytes(32));$_SESSION['passenger_facebook_oauth_state']=$state;$_SESSION['passenger_facebook_oauth_started']=time();unset($_SESSION['passenger_facebook_booking']);
 $slug=trim((string)($_GET['slug']??''));$token=trim((string)($_GET['token']??''));if($slug!==''&&preg_match('/^[a-f0-9]{64}$/',$token)){$q=$db->prepare("SELECT tp.id,tp.passenger_profile_id,tp.organization_id,t.slug FROM tour_passengers tp JOIN tours t ON t.id=tp.tour_id JOIN organizations o ON o.id=t.organization_id WHERE t.slug=? AND tp.booking_access_token_hash=? AND tp.booking_access_token_revoked_at IS NULL AND tp.status='ACTIVE' AND o.status='ACTIVE' LIMIT 1");$q->execute([$slug,hash('sha256',$token)]);if($b=$q->fetch())$_SESSION['passenger_facebook_booking']=['tp_id'=>(int)$b['id'],'profile_id'=>(int)$b['passenger_profile_id'],'organization_id'=>(int)$b['organization_id'],'slug'=>$b['slug']];}
 header('Location: https://www.facebook.com/dialog/oauth?'.http_build_query(['client_id'=>$appId,'redirect_uri'=>$redirectUri,'response_type'=>'code','scope'=>'email','state'=>$state]));exit;
}
$state=(string)($_GET['state']??'');$expected=(string)($_SESSION['passenger_facebook_oauth_state']??'');$started=(int)($_SESSION['passenger_facebook_oauth_started']??0);unset($_SESSION['passenger_facebook_oauth_state'],$_SESSION['passenger_facebook_oauth_started']);if($state===''||$expected===''||!hash_equals($expected,$state)||$started<time()-600){passenger_oauth_rate_fail();fb_fail('The Facebook sign-in session expired. Please try again.');}if(isset($_GET['error'])){passenger_oauth_rate_fail();fb_fail('Facebook sign-in was cancelled or denied.');}$code=(string)($_GET['code']??'');if($code===''){passenger_oauth_rate_fail();fb_fail('Facebook did not return an authorization code.');}
try{$tr=fb_json('https://graph.facebook.com/oauth/access_token',['client_id'=>$appId,'client_secret'=>$appSecret,'redirect_uri'=>$redirectUri,'code'=>$code]);$access=(string)($tr['access_token']??'');if($access==='')throw new RuntimeException('Facebook did not return an access token.');$me=fb_json('https://graph.facebook.com/me?'.http_build_query(['fields'=>'id,name,email','access_token'=>$access]));$subject=trim((string)($me['id']??''));$email=strtolower(trim((string)($me['email']??'')));if($subject===''||$email===''||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('A Facebook account with a verified email address is required.');$booking=$_SESSION['passenger_facebook_booking']??null;unset($_SESSION['passenger_facebook_booking']);
$db->beginTransaction();$q=$db->prepare("SELECT pa.id,pa.organization_id,pa.passenger_profile_id,pa.email,pa.status FROM passenger_auth_identities i JOIN passenger_accounts pa ON pa.id=i.passenger_account_id WHERE i.provider='FACEBOOK' AND i.provider_subject=? LIMIT 2 FOR UPDATE");$q->execute([$subject]);$irs=$q->fetchAll();if(count($irs)>1)throw new RuntimeException('This Facebook identity is linked more than once. Contact the organizer.');$account=null;
if($irs){$account=$irs[0];if($account['status']!=='ACTIVE')throw new RuntimeException('This passenger account is not active.');if(strtolower((string)$account['email'])!==$email)throw new RuntimeException('Facebook email does not match the linked account.');}
elseif($booking){$q=$db->prepare("SELECT pa.id,pa.organization_id,pa.passenger_profile_id,pa.email,pa.status FROM passenger_accounts pa WHERE pa.organization_id=? AND pa.passenger_profile_id=? LIMIT 1 FOR UPDATE");$q->execute([$booking['organization_id'],$booking['profile_id']]);$account=$q->fetch()?:null;if($account&&$account['status']!=='ACTIVE')throw new RuntimeException('The passenger account is not active.');if($account&&strtolower((string)$account['email'])!==$email)throw new RuntimeException('This Facebook email does not match the passenger profile email.');if(!$account){$q=$db->prepare("SELECT id FROM passenger_accounts WHERE organization_id=? AND LOWER(email)=LOWER(?) LIMIT 1 FOR UPDATE");$q->execute([$booking['organization_id'],$email]);if($q->fetch())throw new RuntimeException('This email already belongs to another passenger account in this organization.');$hash=password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT);$q=$db->prepare("INSERT INTO passenger_accounts(organization_id,passenger_profile_id,email,password_hash,status,email_verified_at) VALUES(?,?,?,?, 'ACTIVE',NOW())");$q->execute([$booking['organization_id'],$booking['profile_id'],$email,$hash]);$account=['id'=>(int)$db->lastInsertId(),'organization_id'=>$booking['organization_id'],'passenger_profile_id'=>$booking['profile_id'],'email'=>$email,'status'=>'ACTIVE'];}}
else{$q=$db->prepare("SELECT pa.id,pa.organization_id,pa.passenger_profile_id,pa.email,pa.status FROM passenger_accounts pa WHERE LOWER(pa.email)=LOWER(?) LIMIT 2 FOR UPDATE");$q->execute([$email]);$rows=$q->fetchAll();if(count($rows)!==1)throw new RuntimeException('We could not uniquely identify your passenger account. Open your tour booking link first, or contact the organizer.');$account=$rows[0];if($account['status']!=='ACTIVE')throw new RuntimeException('This passenger account is not active.');}
if(!$account)throw new RuntimeException('Passenger account could not be resolved.');$q=$db->prepare("SELECT passenger_profile_id,organization_id FROM passenger_accounts WHERE id=? LIMIT 1 FOR UPDATE");$q->execute([(int)$account['id']]);$va=$q->fetch();if(!$va)throw new RuntimeException('Passenger account not found.');if($booking&&((int)$va['organization_id']!==(int)$booking['organization_id']||(int)$va['passenger_profile_id']!==(int)$booking['profile_id']))throw new RuntimeException('This Facebook account cannot be linked to this booking.');
$q=$db->prepare("SELECT id FROM passenger_auth_identities WHERE passenger_account_id=? AND provider='FACEBOOK' LIMIT 1 FOR UPDATE");$q->execute([(int)$account['id']]);$existing=$q->fetchColumn();if($existing){$q=$db->prepare("UPDATE passenger_auth_identities SET provider_subject=?,provider_email=?,last_login_at=NOW() WHERE id=?");$q->execute([$subject,$email,(int)$existing]);}else{$q=$db->prepare("SELECT id FROM passenger_auth_identities WHERE provider='FACEBOOK' AND provider_subject=? LIMIT 1 FOR UPDATE");$q->execute([$subject]);if($q->fetch())throw new RuntimeException('This Facebook account is already linked to another passenger.');$q=$db->prepare("INSERT INTO passenger_auth_identities(passenger_account_id,provider,provider_subject,provider_email,last_login_at) VALUES(?, 'FACEBOOK',?,?,NOW())");$q->execute([(int)$account['id'],$subject,$email]);}$q=$db->prepare('UPDATE passenger_accounts SET last_login_at=NOW(),email_verified_at=COALESCE(email_verified_at,NOW()) WHERE id=?');$q->execute([(int)$account['id']]);$db->commit();passenger_oauth_rate_success();session_regenerate_id(true);$_SESSION['passenger_account_id']=(int)$account['id'];$_SESSION['passenger_profile_id']=(int)$va['passenger_profile_id'];$_SESSION['passenger_organization_id']=(int)$va['organization_id'];saas_redirect('passenger_dashboard.php');
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();passenger_oauth_rate_fail();fb_fail($e->getMessage());}
