<?php require __DIR__.'/bootstrap.php';require __DIR__.'/bootstrap_auth.php';require_login();$tid=require_tour();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();try{$a=$_POST['action']??'';
 if($a==='add'){ require_permission('payment.create');
  $pid=(int)$_POST['passenger_id'];$amt=(float)$_POST['amount'];$q=db()->prepare("SELECT final_fee,tour_id FROM passengers WHERE id=? AND status='ACTIVE'");$q->execute([$pid]);$p=$q->fetch();$q=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM payments WHERE passenger_id=?");$q->execute([$pid]);$paid=(float)$q->fetchColumn();
  if(!$p||$p['tour_id']!=$tid||$amt<=0||$amt>($p['final_fee']-$paid))throw new Exception('Invalid payment amount.');
  db()->prepare("INSERT INTO payments(passenger_id,amount,method,reference,note,created_by) VALUES(?,?,?,?,?,?)")->execute([$pid,$amt,$_POST['method'],trim($_POST['reference']),trim($_POST['note']),$_SESSION['admin_id']]);audit('ADD_PAYMENT','passenger',$pid,(string)$amt);flash('success','Payment saved.');
 }elseif($a==='update'){
  $id=(int)$_POST['id'];$amt=(float)$_POST['amount'];$q=db()->prepare("SELECT pay.id,pay.passenger_id,p.final_fee,p.tour_id FROM payments pay JOIN passengers p ON p.id=pay.passenger_id WHERE pay.id=? AND p.tour_id=? AND p.status='ACTIVE'");$q->execute([$id,$tid]);$pay=$q->fetch();if(!$pay)throw new Exception('Payment not found.');
  $q=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM payments WHERE passenger_id=? AND id<>?");$q->execute([$pay['passenger_id'],$id]);$other=(float)$q->fetchColumn();
  if($amt<=0||$other+$amt>(float)$pay['final_fee'])throw new Exception('Payment amount exceeds the passenger due limit.');
  $paidAt=trim((string)$_POST['paid_at']);
  $paidAt=$paidAt?str_replace('T',' ',$paidAt).(strlen(str_replace('T',' ',$paidAt))===16?':00':''):date('Y-m-d H:i:s');
  db()->prepare("UPDATE payments SET amount=?,method=?,reference=?,note=?,paid_at=? WHERE id=?")->execute([$amt,$_POST['method'],trim($_POST['reference']),trim($_POST['note']),$paidAt,$id]);audit('UPDATE_PAYMENT','payment',$id,(string)$amt);flash('success','Payment updated.');
 }elseif($a==='delete'){require_permission('payment.delete'); require_permission('payment.delete');
  $id=(int)$_POST['id'];
  $q=db()->prepare("SELECT pay.id,pay.amount,pay.passenger_id,p.name,p.tour_id FROM payments pay JOIN passengers p ON p.id=pay.passenger_id WHERE pay.id=? AND p.tour_id=? AND p.status='ACTIVE'");
  $q->execute([$id,$tid]);$pay=$q->fetch();
  if(!$pay)throw new Exception('Payment not found.');
  db()->prepare("DELETE FROM payments WHERE id=?")->execute([$id]);
  audit('DELETE_PAYMENT','payment',$id,'Deleted payment '.money($pay['amount']).' for '.$pay['name']);
  flash('success','Payment deleted successfully. The amount has been returned to the passenger due.');
 }
}catch(Throwable $e){flash('danger',$e->getMessage());}redirect('payments.php');}
$q=db()->prepare("SELECT p.id,p.name,p.phone,b.name bus_name,s.seat_no,p.final_fee,COALESCE(SUM(pay.amount),0) paid FROM passengers p JOIN buses b ON b.id=p.bus_id JOIN seats s ON s.id=p.seat_id LEFT JOIN payments pay ON pay.passenger_id=p.id WHERE p.tour_id=? AND p.status='ACTIVE' GROUP BY p.id ORDER BY p.id DESC");$q->execute([$tid]);$rows=$q->fetchAll();
$q=db()->prepare("SELECT pay.*,p.name passenger_name,s.seat_no FROM payments pay JOIN passengers p ON p.id=pay.passenger_id JOIN seats s ON s.id=p.seat_id WHERE p.tour_id=? AND p.status='ACTIVE' ORDER BY pay.paid_at DESC,pay.id DESC");$q->execute([$tid]);$history=$q->fetchAll();
?><!doctype html><html><head><?php include __DIR__.'/partials/head.php';?></head><body><?php include __DIR__.'/partials/nav.php';?><main class="wrap"><?php flash_render();?><section class="card"><div class="head"><h2>Payment Summary</h2><a class="btn secondary" href="summary_print.php?tour_id=<?=$tid?>">Print Summary</a></div><div class="table-wrap responsive-table"><table><thead><tr><th>Passenger</th><th>Bus / Seat</th><th>Fee</th><th>Paid</th><th>Due</th><th>Add Payment</th></tr></thead><tbody><?php foreach($rows as $p):$due=max(0,$p['final_fee']-$p['paid']);?><tr><td><b><?=h($p['name'])?></b><br><span class="muted"><?=h($p['phone'])?></span></td><td><?=h($p['bus_name'])?> · <?=h($p['seat_no'])?></td><td><?=money($p['final_fee'])?></td><td><?=money($p['paid'])?></td><td><?=money($due)?></td><td><?php if($due>0):?><form method="post" class="pay-inline"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add"><input type="hidden" name="passenger_id" value="<?=$p['id']?>"><input name="amount" type="number" min="0.01" max="<?=$due?>" step="0.01" placeholder="Amount" required><select name="method"><option>Cash</option><option>bKash</option><option>Nagad</option><option>Bank</option><option>Rocket</option></select><input name="reference" placeholder="Reference"><input name="note" placeholder="Note"><button class="btn primary">Save</button></form><?php else:?><span class="badge">Paid</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card"><div class="head"><div><div class="eyebrow">PAYMENT HISTORY</div><h2>Edit Existing Payments</h2></div><span class="muted">Correct amount, method, reference, note or date. Delete is permanent.</span></div><div class="table-wrap responsive-table"><table><thead><tr><th>Passenger</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Note</th><th>Action</th></tr></thead><tbody><?php foreach($history as $x):?><tr><form method="post" onsubmit="return true"><td data-label="Passenger"><?=h($x['passenger_name'])?> · <?=h($x['seat_no'])?></td><td data-label="Date"><input type="datetime-local" name="paid_at" value="<?=h(date('Y-m-d\TH:i',strtotime($x['paid_at'])))?>"></td><td data-label="Amount"><input type="number" name="amount" min="0.01" step="0.01" value="<?=h($x['amount'])?>"></td><td data-label="Method"><select name="method"><?php foreach(['Cash','bKash','Nagad','Bank','Rocket'] as $m):?><option <?=$x['method']===$m?'selected':''?>><?=$m?></option><?php endforeach;?></select></td><td data-label="Reference"><input name="reference" value="<?=h($x['reference'])?>"></td><td data-label="Note"><input name="note" value="<?=h($x['note'])?>"></td><td data-label="Action"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="id" value="<?=$x['id']?>"><button class="btn secondary" type="submit" name="action" value="update">Update</button><?php if(can("payment.delete")):?><button class="btn danger" type="submit" name="action" value="delete" onclick="return confirm('Delete this payment? This cannot be undone.');">Delete</button><?php endif;?></td></form></tr><?php endforeach;?></tbody></table></div></section>
</main></body></html>
