<?php
declare(strict_types=1);
require __DIR__.'/bootstrap_saas.php';
$db=saas_db();
$slug=trim((string)($_GET['slug']??''));
$token=trim((string)($_GET['token']??''));
if($slug===''||$token===''){http_response_code(404);exit('Booking link is incomplete.');}
$q=$db->prepare("SELECT tp.id tp_id,tp.status,tp.fee,tp.discount,pp.full_name,pp.phone,t.id tour_id,t.name tour_name,t.slug,t.start_date,t.end_date,t.booking_fee,o.currency,o.name organization_name FROM tour_passengers tp JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id JOIN tours t ON t.id=tp.tour_id JOIN organizations o ON o.id=t.organization_id WHERE t.slug=? AND SHA2(CONCAT('seat:',tp.id,':',pp.phone,':',t.id),256)=? AND o.status='ACTIVE' LIMIT 1");
$q->execute([$slug,$token]);$booking=$q->fetch();
if(!$booking||$booking['status']==='CANCELLED'){http_response_code(404);exit('Booking not found.');}
$q=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM payments WHERE tour_id=? AND tour_passenger_id=?');$q->execute([(int)$booking['tour_id'],(int)$booking['tp_id']]);$paid=(float)$q->fetchColumn();
$gross=max(0,(float)$booking['fee']-(float)$booking['discount']);$due=max(0,$gross-$paid);$currency=$booking['currency']?:'BDT';
$msg='';$error='';$intent=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  saas_check_csrf();
  if($booking['status']!=='ACTIVE')throw new RuntimeException('Only active bookings can make a payment.');
  if($due<=0)throw new RuntimeException('This booking has no outstanding balance.');
  $amount=round((float)($_POST['amount']??0),2);$method=strtoupper(trim((string)($_POST['method']??'BKASH')));
  $allowed=['BKASH','NAGAD','ROCKET','CARD','BANK'];
  if($amount<=0||$amount>$due+0.005)throw new RuntimeException('Enter an amount up to the current due of '.number_format($due,2).'.');
  if(!in_array($method,$allowed,true))throw new RuntimeException('Invalid payment method.');
  $db->beginTransaction();
  $q=$db->prepare('SELECT tp.id,tp.fee,tp.discount FROM tour_passengers tp WHERE tp.id=? AND tp.tour_id=? AND tp.status=\'ACTIVE\' FOR UPDATE');$q->execute([(int)$booking['tp_id'],(int)$booking['tour_id']]);$locked=$q->fetch();if(!$locked)throw new RuntimeException('Booking is no longer active.');
  $q=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM payments WHERE tour_id=? AND tour_passenger_id=?');$q->execute([(int)$booking['tour_id'],(int)$booking['tp_id']]);$freshPaid=(float)$q->fetchColumn();$freshDue=max(0,(float)$locked['fee']-(float)$locked['discount']-$freshPaid);
  if($amount>$freshDue+0.005)throw new RuntimeException('The due amount changed. Please try again.');
  $clientRef='CHK-'.date('YmdHis').'-'.bin2hex(random_bytes(5));
  $expires=date('Y-m-d H:i:s',time()+1800);
  $q=$db->prepare('INSERT INTO payment_intents(tour_id,tour_passenger_id,amount,currency,method,status,client_reference,metadata_json,expires_at) VALUES(?,?,?,?,?,?,?,?,?)');
  $q->execute([(int)$booking['tour_id'],(int)$booking['tp_id'],$amount,$currency,$method,'PENDING',$clientRef,json_encode(['source'=>'public_checkout'],JSON_UNESCAPED_UNICODE),$expires]);
  $intent=(int)$db->lastInsertId();$db->commit();
  saas_audit('public.payment_intent_created','payment_intent',$intent,json_encode(['tour_passenger_id'=>(int)$booking['tp_id'],'amount'=>$amount,'method'=>$method,'client_reference'=>$clientRef],JSON_UNESCAPED_UNICODE));
  $msg='Payment request created. Gateway confirmation is the next step; no payment is marked as received until the gateway/webhook verifies it.';
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e->getMessage();}
}
$q=$db->prepare("SELECT id,amount,currency,method,status,client_reference,created_at,expires_at FROM payment_intents WHERE tour_passenger_id=? ORDER BY id DESC LIMIT 10");$q->execute([(int)$booking['tp_id']]);$intents=$q->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payment — <?=saas_h($booking['tour_name'])?></title><style>*{box-sizing:border-box}body{margin:0;background:#f4f7fb;font-family:Inter,Arial,sans-serif;color:#172033}.wrap{max-width:900px;margin:25px auto;padding:0 16px}.card{background:#fff;border-radius:18px;padding:22px;margin-bottom:18px;box-shadow:0 8px 30px #0000000b}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat{border:1px solid #eaecf0;border-radius:12px;padding:15px}.stat b{display:block;font-size:22px;margin-top:5px}.due{font-weight:800}.msg{padding:12px;border-radius:10px;margin-bottom:15px;background:#ecfdf3;color:#067647}.err{padding:12px;border-radius:10px;margin-bottom:15px;background:#fef3f2;color:#b42318}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:block;font-size:13px;font-weight:700;margin:8px 0 5px}input,select,button{width:100%;padding:11px;border:1px solid #d0d5dd;border-radius:9px;font:inherit}button{margin-top:15px;background:#155eef;color:#fff;border-color:#155eef;font-weight:700;cursor:pointer}.muted{font-size:13px;color:#667085}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #eee}.badge{padding:4px 8px;border-radius:999px;background:#eef4ff;color:#175cd3;font-size:12px}@media(max-width:600px){.summary,.fields{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><p><a href="public_room_select.php?slug=<?=rawurlencode($slug)?>&token=<?=rawurlencode($token)?>">← Back to room selection</a></p><section class="card"><h1>Payment</h1><p>Booking for <strong><?=saas_h($booking['full_name'])?></strong> · <?=saas_h($booking['tour_name'])?></p><?php if($msg):?><div class="msg"><?=saas_h($msg)?></div><?php endif;?><?php if($error):?><div class="err"><?=saas_h($error)?></div><?php endif;?><div class="summary"><div class="stat"><span class="muted">Total fee</span><b><?=saas_h($currency)?> <?=number_format($gross,2)?></b></div><div class="stat"><span class="muted">Paid</span><b><?=saas_h($currency)?> <?=number_format($paid,2)?></b></div><div class="stat"><span class="muted">Outstanding</span><b class="due"><?=saas_h($currency)?> <?=number_format($due,2)?></b></div></div></section><?php if($due>0):?><section class="card"><h2>Make a payment</h2><p class="muted">Choose an amount and payment method. This step creates a secure payment intent; it does not record money as received by itself.</p><form method="post"><input type="hidden" name="csrf_token" value="<?=saas_h(saas_csrf())?>"><div class="fields"><div><label>Amount</label><input type="number" name="amount" min="0.01" max="<?=saas_h((string)$due)?>" step="0.01" value="<?=saas_h((string)$due)?>" required></div><div><label>Payment method</label><select name="method"><option>BKASH</option><option>NAGAD</option><option>ROCKET</option><option>CARD</option><option>BANK</option></select></div></div><button type="submit">Continue to payment</button></form></section><?php else:?><section class="card"><h2>Paid in full</h2><p>Your current outstanding balance is zero.</p></section><?php endif;?><section class="card"><h2>Payment requests</h2><?php if(!$intents):?><p class="muted">No payment requests yet.</p><?php else:?><div style="overflow:auto"><table><tr><th>Reference</th><th>Amount</th><th>Method</th><th>Status</th><th>Created</th></tr><?php foreach($intents as $i):?><tr><td><?=saas_h($i['client_reference'])?></td><td><?=saas_h($i['currency'])?> <?=number_format((float)$i['amount'],2)?></td><td><?=saas_h($i['method'])?></td><td><span class="badge"><?=saas_h($i['status'])?></span></td><td><?=saas_h($i['created_at'])?></td></tr><?php endforeach;?></table></div><?php endif;?></section><p class="muted">Payments are only added to your paid balance after verified gateway confirmation.</p></main></body></html>
