<?php
declare(strict_types=1);
require __DIR__.'/bootstrap_saas.php';
$db=saas_db();$slug=trim((string)($_GET['slug']??''));
if($slug===''){http_response_code(404);exit('Tour not found.');}
$q=$db->prepare("SELECT t.*,o.name organization_name,o.currency organization_currency,pp.status page_status,pp.theme_key,pp.title page_title,pp.subtitle,pp.cover_image,pp.logo_image,pp.primary_color,pp.secondary_color,pp.seo_title,pp.seo_description FROM tours t JOIN organizations o ON o.id=t.organization_id JOIN tour_public_pages pp ON pp.tour_id=t.id WHERE t.slug=? AND t.status IN ('DRAFT','ACTIVE','CLOSED') AND pp.status IN ('PUBLISHED','CLOSED') AND o.status='ACTIVE' LIMIT 1");$q->execute([$slug]);$tour=$q->fetch();
if(!$tour){http_response_code(404);exit('Tour not found or registration is not public.');}
$closed=$tour['page_status']==='CLOSED'||$tour['status']==='CLOSED';$error='';$success='';$bookingLink='';
if($_SERVER['REQUEST_METHOD']==='POST'&&!$closed){
 $name=trim((string)($_POST['full_name']??''));$phone=trim((string)($_POST['phone']??''));$email=strtolower(trim((string)($_POST['email']??'')));$fee=(float)$tour['default_fee'];
 if($name===''||$phone==='')$error='Name and phone number are required.';elseif(strlen($name)>180||strlen($phone)>50||strlen($email)>190)$error='One or more fields are too long.';elseif($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$error='Please enter a valid email address.';else try{
  $db->beginTransaction();
  $q=$db->prepare('SELECT id,full_name,email FROM passenger_profiles WHERE organization_id=? AND phone=? ORDER BY id LIMIT 1 FOR UPDATE');$q->execute([(int)$tour['organization_id'],$phone]);$existingProfile=$q->fetch();
  if($existingProfile){
    $profileId=(int)$existingProfile['id'];
    if($email!==''&&$existingProfile['email']!==null&&strtolower((string)$existingProfile['email'])!==$email)throw new RuntimeException('This phone number is already associated with another passenger profile. Please contact the organizer.');
  }else{$q=$db->prepare('INSERT INTO passenger_profiles(organization_id,full_name,phone,email) VALUES(?,?,?,?)');$q->execute([(int)$tour['organization_id'],$name,$phone,$email?:null]);$profileId=(int)$db->lastInsertId();}
  $q=$db->prepare('SELECT id,status FROM tour_passengers WHERE tour_id=? AND passenger_profile_id=? FOR UPDATE');$q->execute([(int)$tour['id'],$profileId]);$existing=$q->fetch();
  if($existing&&$existing['status']!=='CANCELLED')throw new RuntimeException('This passenger is already registered for this tour.');
  $token=bin2hex(random_bytes(32));$tokenHash=hash('sha256',$token);
  if($existing){$q=$db->prepare("UPDATE tour_passengers SET status='PENDING',registration_source='PUBLIC',fee=?,discount=0,booking_access_token_hash=?,booking_access_token_created_at=NOW(),booking_access_token_revoked_at=NULL WHERE id=?");$q->execute([$fee,$tokenHash,(int)$existing['id']]);}
  else{$q=$db->prepare("INSERT INTO tour_passengers(tour_id,passenger_profile_id,status,registration_source,fee,discount,booking_access_token_hash,booking_access_token_created_at) VALUES(?,?, 'PENDING','PUBLIC',?,0,?,NOW())");$q->execute([(int)$tour['id'],$profileId,$fee,$tokenHash]);}
  $db->commit();$base=rtrim(dirname((string)($_SERVER['SCRIPT_NAME']??'/')),'/');$bookingLink=$base.'/public_booking.php?slug='.rawurlencode((string)$tour['slug']).'&token='.rawurlencode($token);$success='Registration submitted successfully. Your booking is pending confirmation.';
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Could not complete registration. Please try again.';}
}
$theme=in_array((string)$tour['theme_key'],['classic','travel','event'],true)?(string)$tour['theme_key']:'classic';$primary=preg_match('/^#[0-9a-fA-F]{6}$/',(string)$tour['primary_color'])?$tour['primary_color']:'#155eef';$secondary=preg_match('/^#[0-9a-fA-F]{6}$/',(string)$tour['secondary_color'])?$tour['secondary_color']:'#0f172a';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?=saas_h($tour['seo_description']?:$tour['page_title']?:$tour['name'])?>"><title><?=saas_h($tour['seo_title']?:$tour['page_title']?:$tour['name'])?></title><style>:root{--primary:<?=saas_h($primary)?>;--secondary:<?=saas_h($secondary)?>}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Arial,sans-serif;background:#f5f7fb;color:#172033}.nav{position:absolute;z-index:3;left:0;right:0;padding:18px 20px;color:#fff}.navin{max-width:1100px;margin:auto;display:flex;justify-content:space-between;align-items:center}.brand{font-weight:900}.nav a{color:#fff;text-decoration:none}.hero{min-height:440px;background:linear-gradient(135deg,var(--secondary),var(--primary));<?php if($tour['cover_image']):?>background-image:linear-gradient(135deg,#000b,#0005),url('<?=saas_h($tour['cover_image'])?>');background-size:cover;background-position:center;<?php endif;?>display:flex;align-items:flex-end;color:#fff}.hero-inner{width:min(1100px,100%);margin:auto;padding:90px 20px 60px}.logo{max-height:65px;max-width:190px;object-fit:contain;margin-bottom:15px}.hero h1{font-size:clamp(34px,6vw,62px);line-height:1.02;margin:10px 0}.hero p{font-size:19px;max-width:720px}.wrap{max-width:1100px;margin:-50px auto 50px;padding:0 20px;position:relative}.card{background:#fff;border-radius:20px;padding:25px;box-shadow:0 10px 35px #00000012;margin-bottom:18px}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.info{display:grid;grid-template-columns:1fr 1fr;gap:12px}.info div{padding:14px;background:#f8fafc;border-radius:12px}.register input,.register button{width:100%;padding:13px;margin:6px 0;border:1px solid #d0d5dd;border-radius:10px;font:inherit}.register button{background:var(--primary);color:#fff;border-color:var(--primary);font-weight:800;cursor:pointer}.msg{padding:12px;border-radius:10px}.ok{background:#ecfdf3;color:#067647}.err{background:#fef3f2;color:#b42318}.closed{padding:14px;background:#fff7ed;color:#9a3412;border-radius:10px;font-weight:700}.muted{color:#667085;font-size:14px}.link{word-break:break-all;background:#f8fafc;padding:12px;border-radius:10px;margin-top:10px}.link a{color:var(--primary);font-weight:700}.cta{display:inline-block;background:#fff;color:var(--secondary);padding:13px 18px;border-radius:12px;text-decoration:none;font-weight:900;margin-top:10px}.theme-travel .hero{min-height:560px}.theme-travel .hero h1{font-weight:800;letter-spacing:-2px}.theme-travel .card{border-radius:24px}.theme-event .hero{min-height:390px;align-items:center}.theme-event .hero-inner{padding-top:120px}.theme-event .hero h1{text-transform:uppercase;letter-spacing:2px}.theme-event .wrap{margin-top:20px}.theme-event .card{border-radius:10px}@media(max-width:750px){.grid,.info{grid-template-columns:1fr}.wrap{margin-top:-25px}.theme-event .wrap{margin-top:15px}.hero{min-height:350px}}
</style></head><body class="theme-<?=saas_h($theme)?>"><nav class="nav"><div class="navin"><div class="brand"><?=saas_h($tour['organization_name'])?></div><a href="passenger_auth.php">Passenger Login</a></div></nav><header class="hero"><div class="hero-inner"><?php if($tour['logo_image']):?><img class="logo" src="<?=saas_h($tour['logo_image'])?>" alt="Logo"><?php endif;?><div style="opacity:.85"><?=saas_h($tour['organization_name'])?></div><h1><?=saas_h($tour['page_title']?:$tour['name'])?></h1><p><?=saas_h($tour['subtitle']?:($tour['description']?:'Join us for this tour.'))?></p><?php if(!$closed):?><a class="cta" href="#register">Register / Book Now →</a><?php else:?><div class="closed">Registration is currently closed.</div><?php endif;?></div></header><main class="wrap"><div class="grid"><section class="card"><h2>Tour information</h2><div class="info"><div><strong>Start</strong><br><?=saas_h($tour['start_date']?:'To be announced')?></div><div><strong>End</strong><br><?=saas_h($tour['end_date']?:'To be announced')?></div><div><strong>Tour fee</strong><br><?=number_format((float)$tour['default_fee'],2)?> <?=saas_h($tour['organization_currency']?:'BDT')?></div><div><strong>Booking status</strong><br><?=($closed?'Closed':'Open')?></div></div><?php if($tour['description']):?><p><?=nl2br(saas_h($tour['description']))?></p><?php endif;?></section><section class="card register" id="register"><h2>Register now</h2><?php if($success):?><div class="msg ok"><?=saas_h($success)?></div><p class="muted">Save your private booking link. It becomes your secure booking access after the organizer confirms you.</p><div class="link"><a href="<?=saas_h($bookingLink)?>">Open your booking</a><br><span><?=saas_h($bookingLink)?></span></div><?php elseif($closed):?><div class="closed">Registration is currently closed.</div><?php else:?><?php if($error):?><div class="msg err"><?=saas_h($error)?></div><?php endif;?><form method="post"><label>Full name *</label><input name="full_name" maxlength="180" required autocomplete="name"><label>Phone *</label><input name="phone" maxlength="50" required autocomplete="tel"><label>Email</label><input type="email" name="email" maxlength="190" autocomplete="email"><button>Submit registration</button></form><p class="muted">Your registration remains pending until the tour organizer confirms it.</p><?php endif;?></section></div></main></body></html>