<?php
require_once __DIR__.'/bootstrap_saas.php';
$tourId=saas_require_tour();saas_require_permission('bus.manage');$db=saas_db();$error='';$ok='';
if($_SERVER['REQUEST_METHOD']==='POST'){saas_check_csrf();try{if(($_POST['action']??'')==='create_bus'){
$name=trim((string)($_POST['name']??''));$number=trim((string)($_POST['bus_number']??''));$layout=(string)($_POST['layout_type']??'2+2');$rows=max(1,(int)($_POST['normal_rows']??0));$front=max(0,(int)($_POST['front_single_count']??0));$last=max(1,(int)($_POST['last_row_seats']??0));$per=['1+2'=>3,'2+1'=>3,'2+2'=>4,'2+3'=>5,'LEGACY5'=>5][$layout]??4;if($name==='')throw new RuntimeException('Bus name is required.');
$total=$front+$rows*$per+$last;$db->beginTransaction();$q=$db->prepare('INSERT INTO buses(tour_id,name,bus_number,layout_type,total_seats,normal_rows,front_single_count,last_row_seats) VALUES(?,?,?,?,?,?,?,?)');$q->execute([$tourId,$name,$number?:null,$layout,$total,$rows,$front,$last]);$busId=(int)$db->lastInsertId();$q=$db->prepare('INSERT INTO seats(bus_id,seat_code,row_no,position) VALUES(?,?,?,?)');$n=0;
for($i=1;$i<=$front;$i++){$n++;$q->execute([$busId,'S'.$i,0,'FRONT']);}for($r=1;$r<=$rows;$r++){for($p=1;$p<=$per;$p++){$n++;$q->execute([$busId,chr(64+$r).$p,$r,$p]);}}$lastRow=$rows+1;for($p=1;$p<=$last;$p++){$n++;$q->execute([$busId,'L'.$p,$lastRow,$p]);}$db->commit();saas_audit('bus.created','bus',$busId,json_encode(['name'=>$name,'layout'=>$layout]));$ok='Bus created with '.$n.' seats.';}}
catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e->getMessage();}}
$q=$db->prepare('SELECT * FROM buses WHERE tour_id=? ORDER BY id');$q->execute([$tourId]);$buses=$q->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Buses &amp; Seats</title><style>body{font-family:Arial;background:#f5f7fb;margin:0;color:#172033}.wrap{max-width:1100px;margin:30px auto;padding:0 18px}.box{background:#fff;padding:22px;border-radius:14px;margin-bottom:20px;box-shadow:0 5px 20px #0000000d}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}input,select,button{width:100%;box-sizing:border-box;padding:11px;margin-top:6px;margin-bottom:12px}button{cursor:pointer}.msg{padding:10px;background:#ecfdf3;color:#067647}.err{padding:10px;background:#fef3f2;color:#b42318}.bus{border-top:1px solid #eee;padding:15px 0}.seats{display:flex;flex-wrap:wrap;gap:7px}.seat{padding:7px 9px;background:#eef2ff;border-radius:7px;font-size:13px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap"><h1>Buses &amp; Seats</h1><?php if($ok):?><div class="msg box"><?=saas_h($ok)?></div><?php endif;?><?php if($error):?><div class="err box"><?=saas_h($error)?></div><?php endif;?><section class="box"><h2>Add bus</h2><form method="post"><input type="hidden" name="csrf" value="<?=saas_h(saas_csrf())?>"><input type="hidden" name="action" value="create_bus"><label>Bus name</label><input name="name" placeholder="Premium Coach" required><label>Bus number</label><input name="bus_number" placeholder="Dhaka Metro ..."><label>Layout</label><select name="layout_type"><option value="2+2">2 + 2</option><option value="2+3">2 + 3</option><option value="1+2">1 + 2 Premium</option><option value="2+1">2 + 1 Premium</option><option value="LEGACY5">Legacy 5-seat</option></select><div class="grid"><div><label>Normal rows</label><input type="number" name="normal_rows" min="1" value="10" required></div><div><label>Front single seats</label><input type="number" name="front_single_count" min="0" value="0"></div><div><label>Last row seats</label><input type="number" name="last_row_seats" min="1" value="4" required></div></div><button>Create bus &amp; seats</button></form></section><section class="box"><h2>Configured buses</h2><?php foreach($buses as $b):?><div class="bus"><strong><?=saas_h($b['name'])?></strong> — <?=saas_h($b['layout_type'])?> — <?=saas_h($b['total_seats'])?> seats<br><small><?=saas_h($b['bus_number']??'')?></small><div class="seats"><?php $s=$db->prepare('SELECT seat_code FROM seats WHERE bus_id=? ORDER BY row_no,id');$s->execute([$b['id']]);foreach($s as $seat):?><span class="seat"><?=saas_h($seat['seat_code'])?></span><?php endforeach;?></div></div><?php endforeach;if(!$buses):?><p>No buses yet.</p><?php endif;?></section></main></body></html>
