<?php
declare(strict_types=1);
require __DIR__.'/bootstrap_saas.php';
$db=saas_db();
$slug=trim((string)($_GET['slug']??''));$token=trim((string)($_GET['token']??''));
if($slug===''||!preg_match('/^[a-f0-9]{64}$/',$token)){http_response_code(404);exit('Ticket link is invalid.');}
$hash=hash('sha256',$token);
$q=$db->prepare("SELECT tp.id tp_id,tp.status,tp.fee,tp.discount,pp.full_name,pp.phone,t.id tour_id,t.name tour_name,t.slug,t.start_date,t.end_date,o.name organization_name,o.currency,ti.id ticket_id,ti.ticket_number,ti.status ticket_status,ti.template_key,ti.qr_token_hash,ti.issued_at FROM tour_passengers tp JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id JOIN tours t ON t.id=tp.tour_id JOIN organizations o ON o.id=t.organization_id JOIN ticket_instances ti ON ti.tour_passenger_id=tp.id AND ti.status='ISSUED' WHERE t.slug=? AND tp.booking_access_token_hash=? AND tp.booking_access_token_revoked_at IS NULL AND tp.status='ACTIVE' AND o.status='ACTIVE' ORDER BY ti.id DESC LIMIT 1");$q->execute([$slug,$hash]);$ticket=$q->fetch();if(!$ticket){http_response_code(404);exit('Active ticket not found.');}
$q=$db->prepare("SELECT b.name bus_name,b.bus_number,s.seat_code FROM passenger_seat_assignments psa JOIN buses b ON b.id=psa.bus_id JOIN seats s ON s.id=psa.seat_id WHERE psa.tour_passenger_id=? LIMIT 1");$q->execute([(int)$ticket['tp_id']]);$seat=$q->fetch();
$q=$db->prepare("SELECT r.room_no,r.room_type FROM room_assignments ra JOIN rooms r ON r.id=ra.room_id WHERE ra.tour_passenger_id=? LIMIT 1");$q->execute([(int)$ticket['tp_id']]);$room=$q->fetch();
$q=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM payments WHERE tour_id=? AND tour_passenger_id=?');$q->execute([(int)$ticket['tour_id'],(int)$ticket['tp_id']]);$paid=(float)$q->fetchColumn();$total=max(0,(float)$ticket['fee']-(float)$ticket['discount']);$due=max(0,$total-$paid);$currency=$ticket['currency']?:'BDT';
$templates=['classic'=>'Classic','travel'=>'Travel','event'=>'Event'];$template=strtolower(trim((string)($_GET['template']??$ticket['template_key']??'classic')));if(!isset($templates[$template]))$template='classic';
$printLayout=($_GET['layout']??'1up')==='2up'?'2up':'1up';$saveError='';
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['template'])){try{saas_check_csrf();$new=strtolower(trim((string)$_POST['template']));if(!isset($templates[$new]))throw new RuntimeException('Invalid ticket design.');$q=$db->prepare("UPDATE ticket_instances SET template_key=?,updated_at=NOW() WHERE id=? AND tour_passenger_id=? AND status='ISSUED'");$q->execute([$new,(int)$ticket['ticket_id'],(int)$ticket['tp_id']]);$template=$new;saas_audit('public.ticket_template_changed','ticket_instance',(int)$ticket['ticket_id'],json_encode(['template'=>$new],JSON_UNESCAPED_UNICODE));}catch(Throwable $e){$saveError='Could not save the ticket design.';}}
$qrToken=hash_hmac('sha256',(string)$ticket['ticket_number'],saas_app_key());
$qrHash=hash('sha256',$qrToken);if(!hash_equals((string)$ticket['qr_token_hash'],$qrHash)){http_response_code(409);exit('Ticket QR is not synchronized. Please reissue the ticket.');}
$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=(string)($_SERVER['HTTP_HOST']??'');
$verifyUrl=$scheme.'://'.$host.'/ticket_verify.php?ticket='.rawurlencode($ticket['ticket_number']).'&q='.rawurlencode($qrToken);
$qrUrl='https://api.qrserver.com/v1/create-qr-code/?size=300x300&margin=4&data='.rawurlencode($verifyUrl);
$accent=$template==='travel'?'#0b7a75':($template==='event'?'#7c3aed':'#155eef');
$ticketData=['organization'=> $ticket['organization_name'],'tour'=>$ticket['tour_name'],'dates'=>trim((string)$ticket['start_date']).($ticket['end_date']?' — '.(string)$ticket['end_date']:''),'guest'=>$ticket['full_name'],'phone'=>$ticket['phone'],'bus'=>$seat['bus_name']??'Not assigned','bus_number'=>$seat['bus_number']??'—','seat'=>$seat['seat_code']??'Not assigned','room'=>$room?trim((string)$room['room_no'].' · '.(string)$room['room_type']):'Not assigned','paid'=>number_format($paid,2),'due'=>$due<=0?'PAID':$currency.' '.number_format($due,2),'ticket'=>$ticket['ticket_number'],'currency'=>$currency];
function ticket_card(array $d,string $template,string $qrUrl,string $accent): void { ?>
<article class="ticket ticket-<?=saas_h($template)?>">
  <div class="artwork"></div>
  <div class="ticket-overlay">
    <div class="ticket-title"><div class="org"><?=saas_h($d['organization'])?></div><h1><?=saas_h($d['tour'])?></h1><div class="dates"><?=saas_h($d['dates'])?></div></div>
    <div class="guest-block"><div class="label">GUEST NAME</div><div class="guest"><?=saas_h($d['guest'])?></div><div class="phone"><?=saas_h($d['phone'])?></div></div>
    <div class="info-grid">
      <div><span>BUS</span><strong><?=saas_h($d['bus'])?></strong></div><div><span>BUS NO.</span><strong><?=saas_h($d['bus_number'])?></strong></div>
      <div><span>SEAT</span><strong><?=saas_h($d['seat'])?></strong></div><div><span>ROOM</span><strong><?=saas_h($d['room'])?></strong></div>
      <div><span>PAID</span><strong><?=saas_h($d['currency'])?> <?=saas_h($d['paid'])?></strong></div><div><span>DUE</span><strong class="due"><?=saas_h($d['due'])?></strong></div>
    </div>
    <div class="ticket-no">TICKET <?=saas_h($d['ticket'])?></div>
    <div class="qr-frame"><img src="<?=saas_h($qrUrl)?>" alt="Ticket QR"></div>
  </div>
</article>
<?php }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ticket <?=saas_h($ticket['ticket_number'])?></title><style>
@page{size:A4 landscape;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;font-family:Arial,sans-serif;color:#182230;background:#eef2f6}.controls{max-width:1050px;margin:16px auto;padding:12px 16px;background:#fff;border:1px solid #d0d5dd;border-radius:12px;display:flex;gap:10px;align-items:center;justify-content:center;flex-wrap:wrap}.controls select,.controls button{padding:9px 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.controls button{cursor:pointer;font-weight:700}.controls .primary{background:<?=saas_h($accent)?>;color:#fff;border-color:<?=saas_h($accent)?>}.ok{width:100%;text-align:center;color:#067647}.sheet{width:297mm;margin:20px auto}.ticket{width:297mm;height:118.8mm;position:relative;overflow:hidden;background:#fff;page-break-inside:avoid}.artwork{position:absolute;inset:0;background-image:url('assets/ticket-template1.jpg');background-size:100% 100%;background-repeat:no-repeat}.ticket-overlay{position:absolute;inset:0;color:#111}.ticket-travel .artwork{filter:hue-rotate(20deg) saturate(.92)}.ticket-event .artwork{filter:hue-rotate(280deg) saturate(.86)}
/* The source artwork is 1983x793 (2.5:1), so these overlays stay proportional when printed. */
.ticket-title{position:absolute;left:4.5%;top:6.5%;width:51%;text-shadow:0 1px 2px #fff}.ticket-title .org{font-size:2.2mm;font-weight:700;text-transform:uppercase;letter-spacing:.25mm}.ticket-title h1{margin:.8mm 0;font-size:7.2mm;line-height:1.05}.ticket-title .dates{font-size:2.5mm;font-weight:700}.guest-block{position:absolute;left:30.5%;top:40%;width:34%;padding:2.5mm 3mm;background:#ffffffd9;border-radius:2mm;border-left:1.2mm solid <?=saas_h($accent)?>}.label,.info-grid span{font-size:1.8mm;letter-spacing:.2mm;color:#475467;font-weight:700}.guest{font-size:5mm;font-weight:800;line-height:1.05;margin-top:.8mm}.phone{font-size:2.4mm;margin-top:.8mm}.info-grid{position:absolute;left:30.5%;top:61%;width:43%;display:grid;grid-template-columns:1fr 1fr;gap:1.4mm}.info-grid>div{background:#ffffffdc;border-radius:1.4mm;padding:1.5mm 2mm;min-height:8.5mm}.info-grid span{display:block}.info-grid strong{display:block;font-size:2.8mm;margin-top:.6mm;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.due{color:#b42318}.ticket-no{position:absolute;left:30.5%;bottom:4.5%;font-size:1.9mm;font-weight:800;letter-spacing:.15mm;background:#fffdf0e6;padding:1.2mm 2mm;border-radius:1mm}.qr-frame{position:absolute;right:4.2%;top:38%;width:25mm;height:25mm;display:flex;align-items:center;justify-content:center;background:#fff;padding:1mm;border-radius:1mm}.qr-frame img{width:100%;height:100%;display:block}.ticket-2up{width:210mm;height:84mm}.ticket-2up .ticket-title h1{font-size:5.1mm}.ticket-2up .guest{font-size:3.5mm}.ticket-2up .info-grid strong{font-size:2mm}.ticket-2up .qr-frame{width:20mm;height:20mm}.two-up-sheet{width:210mm;height:168mm;margin:0 auto;display:flex;flex-direction:column}.cut-line{height:0;border-top:1px dashed #777;position:relative}.cut-line:after{content:'CUT';position:absolute;left:50%;top:-2.5mm;transform:translateX(-50%);background:#fff;padding:0 2mm;font-size:1.8mm;color:#777}.two-up-sheet .ticket{flex:0 0 84mm}.two-up-sheet .ticket:first-child{border-bottom:0}.two-up-sheet .ticket:last-child{margin-top:0}.two-up-sheet .cut-line{flex:0 0 0}
@media print{html,body{background:#fff}.controls{display:none}.sheet{margin:0}.one-up .sheet{width:297mm}.two-up .two-up-sheet{width:210mm;height:168mm}.two-up .ticket{width:210mm;height:84mm}.two-up .ticket-overlay{transform:none}.two-up .cut-line{display:block}}
@media(max-width:1000px){.sheet,.ticket{width:100%;height:auto;aspect-ratio:2.5}.ticket-title h1{font-size:clamp(20px,4vw,34px)}.qr-frame{width:18%;height:auto;aspect-ratio:1}.two-up-sheet{width:100%;height:auto}.two-up-sheet .ticket{width:100%;height:auto;aspect-ratio:2.5}.two-up-sheet .cut-line{display:none}}
</style></head><body>
<div class="controls"><form method="post" style="display:inline-flex;gap:8px;align-items:center"><input type="hidden" name="csrf" value="<?=saas_h(saas_csrf())?>"><label>Design <select name="template"><option value="classic" <?=($template==='classic'?'selected':'')?>>Classic</option><option value="travel" <?=($template==='travel'?'selected':'')?>>Travel</option><option value="event" <?=($template==='event'?'selected':'')?>>Event</option></select></label><button type="submit">Save design</button></form><a href="?slug=<?=rawurlencode($slug)?>&token=<?=rawurlencode($token)?>&template=<?=rawurlencode($template)?>&layout=1up"><button type="button">1 ticket / A4 landscape</button></a><a href="?slug=<?=rawurlencode($slug)?>&token=<?=rawurlencode($token)?>&template=<?=rawurlencode($template)?>&layout=2up"><button type="button" class="primary">2 tickets / A4 portrait</button></a><button type="button" class="primary" onclick="window.print()">Print</button><?php if($saveError):?><div class="ok"><?=saas_h($saveError)?></div><?php endif;?></div>
<?php if($printLayout==='2up'): ?><main class="two-up-sheet"><div class="ticket-wrap"><?php ticket_card($ticketData,$template,$qrUrl,$accent); ?></div><div class="cut-line"></div><div class="ticket-wrap"><?php ticket_card($ticketData,$template,$qrUrl,$accent); ?></div></main><?php else: ?><main class="sheet one-up"><?php ticket_card($ticketData,$template,$qrUrl,$accent); ?></main><?php endif; ?>
</body></html>