<?php
require_once __DIR__.'/bootstrap_saas.php';
$tourId=saas_require_tour();
saas_require_permission('bus.manage');
$db=saas_db();
$busId=(int)($_GET['bus_id']??0);
if(!$busId){$q=$db->prepare('SELECT id FROM buses WHERE tour_id=? ORDER BY id LIMIT 1');$q->execute([$tourId]);$busId=(int)$q->fetchColumn();}
$q=$db->prepare('SELECT * FROM buses WHERE id=? AND tour_id=?');$q->execute([$busId,$tourId]);$bus=$q->fetch();
if(!$bus){http_response_code(404);exit('Bus not found.');}
$q=$db->prepare("SELECT s.*,pa.tour_passenger_id,tp.status AS passenger_status,pp.full_name,pp.phone FROM seats s LEFT JOIN passenger_seat_assignments pa ON pa.seat_id=s.id AND pa.bus_id=s.bus_id LEFT JOIN tour_passengers tp ON tp.id=pa.tour_passenger_id AND tp.tour_id=? LEFT JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id WHERE s.bus_id=? ORDER BY s.row_no,s.id");$q->execute([$tourId,$busId]);$seats=$q->fetchAll();
$q=$db->prepare("SELECT tp.id,pp.full_name,pp.phone,pa.seat_id FROM tour_passengers tp JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id LEFT JOIN passenger_seat_assignments pa ON pa.tour_passenger_id=tp.id WHERE tp.tour_id=? AND tp.status<>'CANCELLED' ORDER BY pp.full_name");$q->execute([$tourId]);$passengers=$q->fetchAll();
$q=$db->prepare('SELECT id,name,layout_type,total_seats FROM buses WHERE tour_id=? ORDER BY id');$q->execute([$tourId]);$buses=$q->fetchAll();
$bySeat=[];foreach($seats as $s)$bySeat[(int)$s['id']=$s;
$rows=[];foreach($seats as $s)$rows[(int)$s['row_no']][]=$s;
function row_label($n){if($n<=0)return 'Front';$out='';while($n>0){$n--; $out=chr(65+$n%26).$out;$n=intdiv($n,26);}return $out;}
function seat_html($s){$occupied=!empty($s['tour_passenger_id']);$title=$occupied?($s['full_name'].' · '.$s['phone']):'Available';$cls=$occupied?'seat occupied':'seat available';return '<button type="button" class="'.$cls.'" data-seat="'.(int)$s['id'].'" data-code="'.saas_h($s['seat_code']).'" title="'.saas_h($title).'">'.saas_h($s['seat_code']).'<small>'.($occupied?saas_h(mb_substr($s['full_name'],0,12)):'Available').'</small></button>';}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Seat Plan — <?=saas_h($bus['name'])?></title><style>
*{box-sizing:border-box}body{font-family:Inter,Arial,sans-serif;background:#f4f7fb;margin:0;color:#172033}.wrap{max-width:1200px;margin:24px auto;padding:0 16px}.box{background:#fff;border-radius:16px;padding:20px;margin-bottom:18px;box-shadow:0 6px 22px #0000000b}.top{display:flex;justify-content:space-between;gap:15px;align-items:center;flex-wrap:wrap}.top h1{margin:0 0 5px}.muted{color:#667085}.controls{display:grid;grid-template-columns:260px 1fr 180px;gap:12px;align-items:end}.controls select,.controls button{width:100%;padding:11px;border:1px solid #d0d5dd;border-radius:9px;background:#fff}.controls button{background:#172033;color:#fff;border-color:#172033;cursor:pointer}.search{padding:11px;border:1px solid #d0d5dd;border-radius:9px;width:100%}.legend{display:flex;gap:16px;flex-wrap:wrap;margin:15px 0;font-size:13px}.dot{display:inline-block;width:13px;height:13px;border-radius:4px;vertical-align:-2px;margin-right:5px}.free{background:#eef2ff}.taken{background:#d1fadf}.selected{background:#fde68a}.coach{max-width:620px;margin:25px auto;padding:25px 18px 18px;border:2px solid #d0d5dd;border-radius:32px;background:#fafafa;position:relative}.driver{width:100%;text-align:center;border-bottom:1px dashed #98a2b3;padding:5px 0 16px;margin-bottom:14px;font-weight:700;color:#667085}.row{display:grid;grid-template-columns:1fr 24px 1fr;gap:8px;margin:9px 0}.row.one-left{grid-template-columns:1fr 24px 1fr}.side{display:flex;gap:7px}.side.right{justify-content:flex-start}.aisle{min-height:44px}.seat{border:1px solid #cfd4dc;border-radius:9px;min-height:52px;padding:5px 4px;cursor:pointer;background:#eef2ff;font-weight:700;font-size:12px}.seat small{display:block;font-weight:400;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:4px}.seat.occupied{background:#d1fadf;border-color:#86efac}.seat.active{outline:3px solid #f59e0b}.front,.last{display:flex;gap:7px;margin:10px 0}.front .seat,.last .seat{min-width:58px}.last{border-top:1px dashed #98a2b3;padding-top:12px;justify-content:center}.passenger{display:grid;grid-template-columns:1fr 180px;gap:10px;align-items:end}.passenger select{width:100%;padding:11px;border:1px solid #d0d5dd;border-radius:9px}.assign{padding:11px;border:0;border-radius:9px;background:#155eef;color:white;cursor:pointer}.danger{background:#fff1f0;color:#b42318;border:1px solid #fecdca}.status{margin-top:10px;min-height:20px}.buses a{text-decoration:none;color:inherit}.buslink{display:inline-block;padding:8px 12px;border-radius:9px;background:#f2f4f7;margin:4px}.buslink.current{background:#172033;color:#fff}@media(max-width:700px){.controls,.passenger{grid-template-columns:1fr}.coach{padding:18px 8px}.row{grid-template-columns:1fr 14px 1fr}.seat{min-height:48px;font-size:11px}.side{gap:4px}}
</style></head><body><main class="wrap"><section class="box top"><div><h1>Visual Seat Plan</h1><div class="muted"><?=saas_h($bus['name'])?> · <?=saas_h($bus['layout_type'])?> · <?=saas_h($bus['total_seats'])?> seats</div></div><div class="buses"><?php foreach($buses as $b):?><a class="buslink <?=((int)$b['id']===$busId?'current':'')?>" href="?bus_id=<?=((int)$b['id'])?>"><?=saas_h($b['name'])?></a><?php endforeach;?></div></section>
<section class="box"><div class="controls"><div><label>Passenger</label><select id="passenger"><option value="">Select passenger</option><?php foreach($passengers as $p):?><option value="<?=((int)$p['id'])?>" data-seat="<?=((int)($p['seat_id']??0))?>"><?=saas_h($p['full_name'])?><?=!empty($p['phone'])?' — '.saas_h($p['phone']):''?></option><?php endforeach;?></select></div><div><label>Search</label><input class="search" id="search" placeholder="Search passenger by name or phone"></div><button id="clear">Clear selection</button></div><div class="legend"><span><i class="dot free"></i>Available</span><span><i class="dot taken"></i>Occupied</span><span><i class="dot selected"></i>Selected</span></div><div class="status" id="status"></div></section>
<section class="box"><div class="coach"><div class="driver">FRONT / DRIVER</div><?php if(!empty($rows[0])):?><div class="front"><?php foreach($rows[0] as $s)echo seat_html($s);?></div><?php endif;?><?php $normalRows=[];foreach($rows as $rn=>$items)if($rn>0 && $rn<=((int)$bus['normal_rows']))$normalRows[$rn]=$items;foreach($normalRows as $rn=>$items):$per=count($items);$leftCount=$per>=5?2:($per>=3?1:0);$left=array_slice($items,0,$leftCount);$right=array_slice($items,$leftCount);?><div class="row"><div class="side"><?php foreach($left as $s)echo seat_html($s);?></div><div class="aisle"></div><div class="side right"><?php foreach($right as $s)echo seat_html($s);?></div></div><?php endforeach;if(!empty($rows[((int)$bus['normal_rows'])+1])):?><div class="last"><?php foreach($rows[((int)$bus['normal_rows'])+1] as $s)echo seat_html($s);?></div><?php endif;?></div></section>
<section class="box"><div class="passenger"><div><strong>How to assign</strong><div class="muted">Select a passenger, then tap an available seat. Tapping an occupied seat will select that passenger for reassignment.</div></div><button class="assign" id="assignBtn" disabled>Assign selected seat</button></div></section></main><script>
const csrf=<?=json_encode(saas_csrf())?>, busId=<?=json_encode($busId)?>;let selectedSeat=0;
const statusEl=document.getElementById('status'), passenger=document.getElementById('passenger'), search=document.getElementById('search');
function status(t,ok=false){statusEl.textContent=t;statusEl.style.color=ok?'#067647':'#b42318'}
function refresh(){document.querySelectorAll('.seat').forEach(x=>x.classList.remove('active'));selectedSeat=0;document.getElementById('assignBtn').disabled=true}
document.querySelectorAll('.seat').forEach(btn=>btn.addEventListener('click',()=>{if(!passenger.value){status('Select a passenger first.');return}document.querySelectorAll('.seat').forEach(x=>x.classList.remove('active'));btn.classList.add('active');selectedSeat=Number(btn.dataset.seat);document.getElementById('assignBtn').disabled=false;status('Seat '+btn.dataset.code+' selected.',true)}));
document.getElementById('assignBtn').addEventListener('click',async()=>{if(!passenger.value||!selectedSeat)return;const fd=new FormData();fd.append('csrf',csrf);fd.append('tour_passenger_id',passenger.value);fd.append('bus_id',busId);fd.append('seat_id',selectedSeat);try{const r=await fetch('saas_seat_assign.php',{method:'POST',body:fd,credentials:'same-origin'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Assignment failed');status(j.message||'Seat assigned.',true);setTimeout(()=>location.reload(),350)}catch(e){status(e.message)}});
document.getElementById('clear').addEventListener('click',refresh);search.addEventListener('input',()=>{const q=search.value.toLowerCase();[...passenger.options].forEach((o,i)=>{if(i===0)return;o.hidden=q!==''&&!o.text.toLowerCase().includes(q)})});
</script></body></html>
