<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap_saas.php';
saas_require_login();
$tourId=saas_require_tour(); $orgId=saas_current_organization_id(); saas_require_permission('passenger.create'); $db=saas_db(); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 saas_check_csrf();
 $name=trim((string)($_POST['full_name']??'')); $phone=trim((string)($_POST['phone']??'')); $email=trim((string)($_POST['email']??'')); $fee=max(0,(float)($_POST['fee']??0)); $discount=max(0,(float)($_POST['discount']??0));
 if($name==='') $error='Passenger name is required.'; elseif($discount>$fee) $error='Discount cannot exceed fee.'; else try{
  $db->beginTransaction();
  $q=$db->prepare('INSERT INTO passenger_profiles(organization_id,full_name,phone,email) VALUES(?,?,?,?)'); $q->execute([$orgId,$name,$phone?:null,$email?:null]); $profile=(int)$db->lastInsertId();
  $q=$db->prepare("INSERT INTO tour_passengers(tour_id,passenger_profile_id,registration_source,fee,discount,status) VALUES(?,?, 'ADMIN',?,?, 'ACTIVE')"); $q->execute([$tourId,$profile,$fee,$discount]); $id=(int)$db->lastInsertId();
  $db->commit(); saas_audit('passenger.created','tour_passenger',$id,json_encode(['name'=>$name],JSON_UNESCAPED_UNICODE));
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error='Could not register passenger. They may already be registered for this tour.';}
}
$q=$db->prepare('SELECT tp.id,tp.status,tp.fee,tp.discount,pp.full_name,pp.phone,pp.email FROM tour_passengers tp JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id WHERE tp.tour_id=? ORDER BY tp.id DESC');$q->execute([$tourId]);$passengers=$q->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Passengers</title><style>body{font-family:system-ui;background:#f5f7fb;margin:0;color:#172033}.wrap{max-width:1050px;margin:30px auto;padding:0 18px}.grid{display:grid;grid-template-columns:340px 1fr;gap:20px}.box{background:#fff;padding:22px;border-radius:14px;box-shadow:0 5px 20px #0001}label{display:block;margin:11px 0 5px;font-weight:600}input,button{width:100%;box-sizing:border-box;padding:11px;border:1px solid #ccd3df;border-radius:8px}button{margin-top:15px;background:#172033;color:#fff;border:0;font-weight:700}.err{background:#fff0f0;color:#a22;padding:10px;border-radius:8px;margin-bottom:12px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #eee;text-align:left}@media(max-width:750px){.grid{grid-template-columns:1fr}table{font-size:13px}}</style></head><body><main class="wrap"><p><a href="saas_dashboard.php">← Dashboard</a></p><h1>Passengers</h1><?php if($error):?><div class="err"><?=saas_h($error)?></div><?php endif;?><div class="grid"><section class="box"><h2>Register passenger</h2><form method="post"><input type="hidden" name="csrf" value="<?=saas_h(saas_csrf())?>"><label>Full name</label><input name="full_name" required><label>Phone</label><input name="phone"><label>Email</label><input type="email" name="email"><label>Tour fee</label><input type="number" min="0" step="0.01" name="fee" value="0"><label>Discount</label><input type="number" min="0" step="0.01" name="discount" value="0"><button>Register passenger</button></form></section><section class="box"><h2>Registered passengers</h2><table><tr><th>Name</th><th>Phone</th><th>Fee</th><th>Due</th><th>Status</th></tr><?php foreach($passengers as $p): $due=max(0,(float)$p['fee']-(float)$p['discount']); $pq=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM payments WHERE tour_passenger_id=?');$pq->execute([$p['id']]);$due-=min($due,(float)$pq->fetchColumn());?><tr><td><?=saas_h($p['full_name'])?></td><td><?=saas_h($p['phone']??'')?></td><td><?=number_format((float)$p['fee'],2)?></td><td><?=number_format(max(0,$due),2)?></td><td><?=saas_h($p['status'])?></td></tr><?php endforeach;?></table><?php if(!$passengers):?><p>No passengers registered yet.</p><?php endif;?></section></div></main></body></html>