<?php
declare(strict_types=1);
require __DIR__.'/bootstrap_saas.php';
saas_require_login();
$tourId=saas_require_tour();
saas_require_permission('passenger.create');
$db=saas_db();$error='';$ok='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 saas_check_csrf();
 try{$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);$q=$db->prepare("SELECT tp.id,tp.status,pp.full_name,pp.phone FROM tour_passengers tp JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id WHERE tp.id=? AND tp.tour_id=? FOR UPDATE");$q->execute([$id,$tourId]);$p=$q->fetch();if(!$p)throw new RuntimeException('Registration not found.');
  if($action==='approve'){$q=$db->prepare("UPDATE tour_passengers SET status='ACTIVE' WHERE id=? AND tour_id=? AND status='PENDING'");$q->execute([$id,$tourId]);if(!$q->rowCount())throw new RuntimeException('Registration is no longer pending.');$ok='Registration approved for '.$p['full_name'].'.';saas_audit('registration.approved','tour_passenger',$id,json_encode(['name'=>$p['full_name']],JSON_UNESCAPED_UNICODE));}
  elseif($action==='waitlist'){$q=$db->prepare("UPDATE tour_passengers SET status='WAITLIST' WHERE id=? AND tour_id=? AND status='PENDING'");$q->execute([$id,$tourId]);$ok='Registration moved to waitlist.';saas_audit('registration.waitlisted','tour_passenger',$id,json_encode(['name'=>$p['full_name']],JSON_UNESCAPED_UNICODE));}
  elseif($action==='cancel'){$q=$db->prepare("UPDATE tour_passengers SET status='CANCELLED' WHERE id=? AND tour_id=? AND status<>'CANCELLED'");$q->execute([$id,$tourId]);$ok='Registration cancelled.';saas_audit('registration.cancelled','tour_passenger',$id,json_encode(['name'=>$p['full_name']],JSON_UNESCAPED_UNICODE));}
  else throw new RuntimeException('Invalid action.');
 }catch(Throwable $e){$error=$e->getMessage();}
}
$q=$db->prepare("SELECT tp.id,tp.status,tp.registration_source,tp.fee,tp.discount,tp.registered_at,pp.full_name,pp.phone,pp.email,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.tour_passenger_id=tp.id AND p.tour_id=?),0) paid FROM tour_passengers tp JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id WHERE tp.tour_id=? ORDER BY FIELD(tp.status,'PENDING','ACTIVE','WAITLIST','CANCELLED'),tp.registered_at DESC");$q->execute([$tourId,$tourId]);$rows=$q->fetchAll();
$pending=array_filter($rows,fn($r)=>$r['status']==='PENDING');$active=array_filter($rows,fn($r)=>$r['status']==='ACTIVE');$waitlist=array_filter($rows,fn($r)=>$r['status']==='WAITLIST');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Registrations</title><style>*{box-sizing:border-box}body{font-family:Inter,Arial,sans-serif;background:#f4f7fb;margin:0;color:#172033}.wrap{max-width:1200px;margin:25px auto;padding:0 16px}.box{background:#fff;border-radius:16px;padding:20px;margin-bottom:18px;box-shadow:0 6px 22px #0000000b}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat{border:1px solid #eaecf0;border-radius:12px;padding:14px}.stat b{display:block;font-size:24px;margin-top:4px}.msg{padding:11px;border-radius:9px;margin-bottom:15px}.ok{background:#ecfdf3;color:#067647}.err{background:#fef3f2;color:#b42318}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #eee;text-align:left;white-space:nowrap}.muted{font-size:13px;color:#667085}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2ff;font-size:12px;font-weight:700}.actions{display:flex;gap:6px}.actions button{padding:6px 9px;border:1px solid #d0d5dd;border-radius:7px;background:#fff;cursor:pointer}.actions .approve{background:#155eef;color:#fff;border-color:#155eef}.actions .cancel{color:#b42318}@media(max-width:700px){.stats{grid-template-columns:1fr}.actions{flex-wrap:wrap}}
</style></head><body><main class="wrap"><p><a href="saas_dashboard.php">← Dashboard</a></p><h1>Registration Management</h1><?php if($ok):?><div class="msg ok"><?=saas_h($ok)?></div><?php endif;?><?php if($error):?><div class="msg err"><?=saas_h($error)?></div><?php endif;?><section class="box stats"><div class="stat"><span class="muted">Pending</span><b><?=count($pending)?></b></div><div class="stat"><span class="muted">Active</span><b><?=count($active)?></b></div><div class="stat"><span class="muted">Waitlist</span><b><?=count($waitlist)?></b></div></section><section class="box"><h2>All registrations</h2><div class="tablewrap"><table><tr><th>Passenger</th><th>Phone</th><th>Source</th><th>Fee</th><th>Paid</th><th>Due</th><th>Status</th><th>Registered</th><th>Actions</th></tr><?php foreach($rows as $r):$due=max(0,(float)$r['fee']-(float)$r['discount']-(float)$r['paid']);?><tr><td><?=saas_h($r['full_name'])?><div class="muted"><?=saas_h($r['email']??'')?></div></td><td><?=saas_h($r['phone']??'')?></td><td><?=saas_h($r['registration_source'])?></td><td><?=number_format((float)$r['fee'],2)?></td><td><?=number_format((float)$r['paid'],2)?></td><td><?=number_format($due,2)?></td><td><span class="badge"><?=saas_h($r['status'])?></span></td><td><?=saas_h($r['registered_at'])?></td><td><div class="actions"><?php if($r['status']==='PENDING'):?><form method="post"><input type="hidden" name="csrf" value="<?=saas_h(saas_csrf())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="approve" name="action" value="approve">Approve</button></form><form method="post"><input type="hidden" name="csrf" value="<?=saas_h(saas_csrf())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button name="action" value="waitlist">Waitlist</button></form><?php endif;?><?php if($r['status']!=='CANCELLED'):?><form method="post" onsubmit="return confirm('Cancel this registration?')"><input type="hidden" name="csrf" value="<?=saas_h(saas_csrf())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="cancel" name="action" value="cancel">Cancel</button></form><?php endif;?></div></td></tr><?php endforeach;?></table><?php if(!$rows):?><p class="muted">No registrations yet.</p><?php endif;?></div></section></main></body></html>
