<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
saas_require_login();
$db=saas_db();$uid=saas_user_id();
$q=$db->prepare('SELECT 1 FROM super_admins WHERE user_id=? LIMIT 1');$q->execute([$uid]);
if(!$q->fetchColumn()){http_response_code(403);exit('403 Forbidden — Super Admin access required.');}
$orgId=(int)($_GET['id']??0);if($orgId<1){http_response_code(400);exit('Invalid organization.');}
$q=$db->prepare("SELECT o.*,u.name owner_name,u.email owner_email,sp.plan_code,sp.name plan_name,sp.monthly_price,sp.yearly_price,sp.currency sub_currency,os.id subscription_id,os.status sub_status,os.billing_cycle,os.current_period_start,os.current_period_end,os.trial_ends_at,os.cancelled_at FROM organizations o LEFT JOIN organization_members om ON om.organization_id=o.id AND om.role='OWNER' AND om.status='ACTIVE' LEFT JOIN users u ON u.id=om.user_id LEFT JOIN organization_subscriptions os ON os.organization_id=o.id LEFT JOIN saas_plans sp ON sp.id=os.plan_id WHERE o.id=? LIMIT 1");
$q->execute([$orgId]);$org=$q->fetch();if(!$org){http_response_code(404);exit('Organization not found.');}
$q=$db->prepare("SELECT u.id,u.name,u.email,u.status,om.role,om.status member_status FROM organization_members om JOIN users u ON u.id=om.user_id WHERE om.organization_id=? ORDER BY om.role,u.name");$q->execute([$orgId]);$members=$q->fetchAll();
$q=$db->prepare("SELECT id,name,slug,start_date,end_date,default_fee FROM tours WHERE organization_id=? ORDER BY id DESC LIMIT 100");$q->execute([$orgId]);$tours=$q->fetchAll();
$q=$db->prepare("SELECT id,invoice_number,status,currency,total,amount_paid,due_at,paid_at,created_at FROM billing_invoices WHERE organization_id=? ORDER BY id DESC LIMIT 50");$q->execute([$orgId]);$invoices=$q->fetchAll();
$q=$db->prepare("SELECT id,action,entity_type,entity_id,details,created_at FROM audit_log WHERE organization_id=? ORDER BY id DESC LIMIT 100");$q->execute([$orgId]);$logs=$q->fetchAll();
$q=$db->prepare("SELECT entitlement_key,entitlement_value FROM saas_plan_entitlements WHERE plan_id=(SELECT plan_id FROM organization_subscriptions WHERE organization_id=? LIMIT 1) ORDER BY entitlement_key");$q->execute([$orgId]);$entitlements=$q->fetchAll();
function h($v){return saas_h($v??'');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoTM — Organization #<?=$orgId?></title><link rel="stylesheet" href="assets/app.css"><style>
body{background:#f5f7fb}.wrap{max-width:1250px;margin:auto;padding:26px 16px 70px}.hero,.panel{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:20px;margin-bottom:16px;box-shadow:0 6px 24px #00000008}.hero{display:flex;justify-content:space-between;gap:20px;align-items:center;flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat{padding:14px;border:1px solid #e5e7eb;border-radius:12px}.num{font-size:24px;font-weight:900;margin-top:5px}.muted{color:#667085;font-size:13px}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #eef0f2;text-align:left;font-size:13px;vertical-align:top}.pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2ff;font-size:11px;font-weight:800}.warn{background:#fff7df;color:#8a5a00}.bad{background:#fef3f2;color:#b42318}.nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.nav a{padding:8px 11px;border:1px solid #d0d5dd;border-radius:8px;background:#fff;text-decoration:none}.code{font-family:monospace;font-size:12px}</style></head><body><main class="wrap">
<div class="nav"><a href="super_admin.php">← Super Admin</a><a href="audit_log.php">Platform Audit</a></div>
<section class="hero"><div><div class="eyebrow">ORGANIZATION #<?=$orgId?></div><h1><?=h($org['name'])?></h1><p class="muted"><?=h($org['slug'])?> · Created <?=h($org['created_at'])?></p></div><div><span class="pill <?=$org['status']==='SUSPENDED'?'warn':($org['status']==='ARCHIVED'?'bad':'')?>"><?=h($org['status'])?></span></div></section>
<section class="grid"><div class="stat"><div class="muted">Owner</div><div class="num" style="font-size:18px"><?=h($org['owner_name']?:'—')?></div><div class="muted"><?=h($org['owner_email']?:'')?></div></div><div class="stat"><div class="muted">Subscription</div><div class="num" style="font-size:18px"><?=h($org['plan_name']?:'No plan')?></div><div class="muted"><?=h($org['sub_status']?:'—')?> · <?=h($org['billing_cycle']?:'—')?></div></div><div class="stat"><div class="muted">Period</div><div class="num" style="font-size:18px"><?=h($org['current_period_end']?:'—')?></div><div class="muted">Start: <?=h($org['current_period_start']?:'—')?></div></div></section>
<section class="panel"><h2>Plan & Entitlements</h2><div class="table-wrap"><table class="table"><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody><?php foreach($entitlements as $e):?><tr><td class="code"><?=h($e['entitlement_key'])?></td><td><?=h($e['entitlement_value'])?></td></tr><?php endforeach;?><?php if(!$entitlements):?><tr><td colspan="2" class="muted">No subscription entitlement data.</td></tr><?php endif;?></tbody></table></div></section>
<section class="panel"><h2>Organization Team (<?=count($members)?>)</h2><div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Email</th><th>Org Role</th><th>User Status</th><th>Membership</th></tr></thead><tbody><?php foreach($members as $m):?><tr><td><?=h($m['name'])?> <span class="muted">#<?=$m['id']?></span></td><td><?=h($m['email'])?></td><td><?=h($m['role'])?></td><td><?=h($m['status'])?></td><td><?=h($m['member_status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Tours (<?=count($tours)?> shown)</h2><div class="table-wrap"><table class="table"><thead><tr><th>Tour</th><th>Dates</th><th>Default Fee</th></tr></thead><tbody><?php foreach($tours as $t):?><tr><td><b><?=h($t['name'])?></b><br><span class="muted">#<?=$t['id']?> · <?=h($t['slug'])?></span></td><td><?=h($t['start_date']?:'—')?> → <?=h($t['end_date']?:'—')?></td><td><?=number_format((float)$t['default_fee'],2)?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><h2>Invoices</h2><div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Status</th><th>Total</th><th>Paid</th><th>Due</th></tr></thead><tbody><?php foreach($invoices as $i):?><tr><td><?=h($i['invoice_number'])?></td><td><?=h($i['status'])?></td><td><?=h($i['currency'])?> <?=number_format((float)$i['total'],2)?></td><td><?=number_format((float)$i['amount_paid'],2)?></td><td><?=h($i['due_at']?:'—')?></td></tr><?php endforeach;?><?php if(!$invoices):?><tr><td colspan="5" class="muted">No invoices.</td></tr><?php endif;?></tbody></table></div></section>
<section class="panel"><h2>Organization Audit</h2><div class="table-wrap"><table class="table"><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody><?php foreach($logs as $l):?><tr><td><?=h($l['created_at'])?></td><td><b><?=h($l['action'])?></b></td><td><?=h($l['entity_type'])?> #<?=h($l['entity_id'])?></td><td><?=h($l['details'])?></td></tr><?php endforeach;?><?php if(!$logs):?><tr><td colspan="4" class="muted">No audit records for this organization.</td></tr><?php endif;?></tbody></table></div></section>
</main></body></html>