<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';saas_require_login();$db=saas_db();$uid=saas_user_id();
$q=$db->prepare('SELECT 1 FROM super_admins WHERE user_id=? LIMIT 1');$q->execute([$uid]);if(!$q->fetchColumn()){http_response_code(403);exit('403 Forbidden — Super Admin access required.');}
$csrf=saas_csrf();$error='';$ok='';
if($_SERVER['REQUEST_METHOD']==='POST'){try{
 saas_check_csrf();$action=(string)($_POST['action']??'');$orgId=(int)($_POST['organization_id']??0);
 if($action==='invoice_create'){
  $number=trim((string)$_POST['invoice_number']);$currency=strtoupper(trim((string)$_POST['currency']));$subtotal=max(0,(float)$_POST['subtotal']);$discount=max(0,(float)$_POST['discount']);$tax=max(0,(float)$_POST['tax']);$due=trim((string)$_POST['due_at']);
  if($orgId<1||$number===''||!preg_match('/^[A-Z0-9][A-Z0-9_-]{2,59}$/',$number)||!preg_match('/^[A-Z]{3}$/',$currency))throw new RuntimeException('Invalid invoice details.');
  $total=max(0,$subtotal-$discount+$tax);$q=$db->prepare('INSERT INTO billing_invoices(organization_id,invoice_number,status,currency,subtotal,discount,tax,total,due_at) VALUES(?,?,?,?,?,?,?,?,?)');$q->execute([$orgId,$number,'OPEN',$currency,$subtotal,$discount,$tax,$total,$due!==''?$due.' 23:59:59':null]);$id=(int)$db->lastInsertId();
  saas_audit('super_admin.invoice_created','billing_invoice',$id,json_encode(['organization_id'=>$orgId,'total'=>$total],JSON_UNESCAPED_UNICODE));$ok='Invoice created.';
 }elseif($action==='invoice_status'){
  $id=(int)$_POST['invoice_id'];$status=strtoupper(trim((string)$_POST['status']));if(!in_array($status,['DRAFT','OPEN','PAID','VOID','UNCOLLECTIBLE'],true))throw new RuntimeException('Invalid invoice status.');
  if($status==='PAID'){$q=$db->prepare("UPDATE billing_invoices SET status='PAID',amount_paid=total,paid_at=COALESCE(paid_at,NOW()) WHERE id=?");$q->execute([$id]);}
  else{$q=$db->prepare('UPDATE billing_invoices SET status=? WHERE id=?');$q->execute([$status,$id]);}
  saas_audit('super_admin.invoice_status','billing_invoice',$id,json_encode(['status'=>$status]));$ok='Invoice status updated.';
 }else throw new RuntimeException('Invalid action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$orgs=$db->query('SELECT id,name FROM organizations ORDER BY name')->fetchAll();
$invoices=$db->query("SELECT i.id,i.invoice_number,i.status,i.currency,i.total,i.amount_paid,i.due_at,i.paid_at,i.created_at,o.id organization_id,o.name organization_name FROM billing_invoices i JOIN organizations o ON o.id=i.organization_id ORDER BY i.id DESC LIMIT 200")->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoTM — Super Admin Billing</title><link rel="stylesheet" href="assets/app.css"><style>
body{background:#f5f7fb}.wrap{max-width:1200px;margin:auto;padding:26px 16px 70px}.nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.nav a{padding:8px 11px;background:#fff;border:1px solid #d0d5dd;border-radius:8px;text-decoration:none}.panel{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:20px;margin-bottom:16px}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.form label{display:grid;gap:5px;font-size:13px;font-weight:700}.form input,.form select{padding:9px;border:1px solid #d0d5dd;border-radius:8px}.btn{padding:9px 12px;background:#155eef;color:#fff;border:1px solid #155eef;border-radius:8px;font-weight:700}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #eef0f2;text-align:left;font-size:13px}.table-wrap{overflow:auto}.muted{color:#667085;font-size:13px}.alert{padding:10px;border-radius:9px;margin-bottom:14px}.ok{background:#ecfdf3;color:#067647}.err{background:#fef3f2;color:#b42318}@media(max-width:800px){.form{grid-template-columns:1fr 1fr}}</style></head><body><main class="wrap"><div class="nav"><a href="super_admin.php">← Super Admin</a><a href="super_admin_plans.php">Entitlements</a><a href="audit_log.php">Audit</a></div>
<section class="panel"><div class="eyebrow">BILLING OPERATIONS</div><h1>Invoice Management</h1><p class="muted">Create manual invoices and manage their lifecycle. Payment-provider integration can update these same records later.</p><?php if($ok):?><div class="alert ok"><?=saas_h($ok)?></div><?php endif;?><?php if($error):?><div class="alert err"><?=saas_h($error)?></div><?php endif;?>
<form method="post" class="form"><input type="hidden" name="csrf" value="<?=saas_h($csrf)?>"><input type="hidden" name="action" value="invoice_create"><label>Organization<select name="organization_id" required><?php foreach($orgs as $o):?><option value="<?=$o['id']?>"><?=saas_h($o['name'])?> (#<?=$o['id']?>)</option><?php endforeach;?></select></label><label>Invoice Number<input name="invoice_number" placeholder="INV-2026-001" required></label><label>Currency<input name="currency" value="BDT" maxlength="3" required></label><label>Due Date<input type="date" name="due_at"></label><label>Subtotal<input type="number" step="0.01" min="0" name="subtotal" value="0" required></label><label>Discount<input type="number" step="0.01" min="0" name="discount" value="0"></label><label>Tax<input type="number" step="0.01" min="0" name="tax" value="0"></label><div style="align-self:end"><button class="btn">Create Invoice</button></div></form></section>
<section class="panel"><h2>Recent invoices</h2><div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Organization</th><th>Total</th><th>Paid</th><th>Status</th><th>Due</th><th>Action</th></tr></thead><tbody><?php foreach($invoices as $i):?><tr><td><b><?=saas_h($i['invoice_number'])?></b><br><span class="muted">#<?=$i['id']?></span></td><td><a href="super_admin_organization.php?id=<?=$i['organization_id']?>"><?=saas_h($i['organization_name'])?></a></td><td><?=saas_h($i['currency'])?> <?=number_format((float)$i['total'],2)?></td><td><?=number_format((float)$i['amount_paid'],2)?></td><td><?=saas_h($i['status'])?></td><td><?=saas_h($i['due_at']?:'—')?></td><td><form method="post" style="display:flex;gap:6px"><input type="hidden" name="csrf" value="<?=saas_h($csrf)?>"><input type="hidden" name="action" value="invoice_status"><input type="hidden" name="invoice_id" value="<?=$i['id']?>"><select name="status"><option>DRAFT</option><option>OPEN</option><option>PAID</option><option>VOID</option><option>UNCOLLECTIBLE</option></select><button class="btn">Save</button></form></td></tr><?php endforeach;?><?php if(!$invoices):?><tr><td colspan="7" class="muted">No invoices yet.</td></tr><?php endif;?></tbody></table></div></section></main></body></html>