<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
saas_require_login();
$orgId=saas_require_organization();$tourId=saas_require_tour();saas_require_permission('passenger.create');$db=saas_db();
$q=$db->prepare("SELECT ti.id ticket_id,ti.ticket_number,ti.qr_token_hash,tp.id tp_id,tp.fee,tp.discount,pp.full_name,pp.phone,t.name tour_name,t.start_date,t.end_date,o.name organization_name,o.currency FROM ticket_instances ti JOIN tour_passengers tp ON tp.id=ti.tour_passenger_id JOIN passenger_profiles pp ON pp.id=tp.passenger_profile_id JOIN tours t ON t.id=tp.tour_id JOIN organizations o ON o.id=t.organization_id WHERE ti.tour_id=? AND ti.organization_id=? AND ti.status='ISSUED' ORDER BY ti.id");
$q->execute([$tourId,$orgId]);$rows=$q->fetchAll();
$dq=$db->prepare('SELECT canvas_width,canvas_height,background_image,elements_json FROM tour_ticket_designs WHERE tour_id=? AND organization_id=? LIMIT 1');$dq->execute([$tourId,$orgId]);$design=$dq->fetch();$elements=$design?json_decode((string)$design['elements_json'],true):null;if(!is_array($elements))$elements=null;if($elements && $design && ((int)($design['canvas_width']??0)!==720 || (int)($design['canvas_height']??0)!==350)){foreach($elements as &$ev){$ev['x']=round(((int)($ev['x']??0))*720/max(1,(int)($design['canvas_width']??1120)));$ev['y']=round(((int)($ev['y']??0))*350/max(1,(int)($design['canvas_height']??448)));$ev['w']=max(1,round(((int)($ev['w']??1))*720/max(1,(int)($design['canvas_width']??1120))));$ev['h']=max(1,round(((int)($ev['h']??1))*350/max(1,(int)($design['canvas_height']??448)));$ev['size']=max(1,round(((int)($ev['size']??12))*0.78));}unset($ev);}
$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=(string)($_SERVER['HTTP_HOST']??'');$verifyBase=$scheme.'://'.$host.'/ticket_verify.php?ticket=';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Print All Tickets</title><style>
@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;background:#fff;font-family:Arial,sans-serif}.controls{padding:12px;text-align:center;background:#f3f6fa;border-bottom:1px solid #ddd;position:sticky;top:0;z-index:10}.controls button{padding:9px 15px;border:0;border-radius:8px;background:#155eef;color:#fff;font-weight:800;cursor:pointer}.sheet{width:210mm;margin:0 auto}.ticket{width:190mm;height:92mm;position:relative;overflow:hidden;page-break-inside:avoid} .three-up-sheet{width:210mm;height:297mm;margin:0 auto;display:grid;grid-template-columns:190mm;grid-template-rows:repeat(3,92mm);row-gap:5mm;padding:7mm 10mm;page-break-after:always;break-after:page}.three-up-sheet .ticket{width:190mm;height:92mm}.artwork{position:absolute;inset:0;background-size:100% 100%;background-repeat:no-repeat}.el{position:absolute;overflow:hidden;white-space:nowrap;display:flex;align-items:center;padding:2px 4px}.qr{padding:0;background:#fff}.qr img{width:100%;height:100%;display:block}.fallback{background:#fff;border:1px solid #ddd;padding:18mm}.fallback-title{font-size:10mm;font-weight:800}.fallback-guest{font-size:7mm;margin-top:8mm}.fallback-info{font-size:4mm;margin-top:8mm}.fallback-qr{position:absolute;right:15mm;top:35mm;width:30mm;height:30mm}@media print{.controls{display:none}}
</style></head><body><div class="controls"><strong><?=count($rows)?> issued tickets</strong> <button onclick="window.print()">Print All</button></div><?php foreach(array_chunk($rows,3) as $sheetRows): ?><section class="three-up-sheet">
<?php foreach($sheetRows as $r):
$q=$db->prepare("SELECT b.name bus_name,b.bus_number,s.seat_code FROM passenger_seat_assignments psa JOIN buses b ON b.id=psa.bus_id JOIN seats s ON s.id=psa.seat_id WHERE psa.tour_passenger_id=? LIMIT 1");$q->execute([(int)$r['tp_id']]);$seat=$q->fetch();
$q=$db->prepare("SELECT r.room_no,r.room_type FROM room_assignments ra JOIN rooms r ON r.id=ra.room_id WHERE ra.tour_passenger_id=? LIMIT 1");$q->execute([(int)$r['tp_id']]);$room=$q->fetch();
$q=$db->prepare('SELECT COALESCE(SUM(amount),0) FROM payments WHERE tour_id=? AND tour_passenger_id=?');$q->execute([$tourId,(int)$r['tp_id']]);$paid=(float)$q->fetchColumn();
$total=max(0,(float)$r['fee']-(float)$r['discount']);$due=max(0,$total-$paid);$cur=$r['currency']?:'BDT';$token=hash_hmac('sha256',(string)$r['ticket_number'],saas_app_key());$verify=$verifyBase.rawurlencode($r['ticket_number']).'&q='.rawurlencode($token);$qr='https://api.qrserver.com/v1/create-qr-code/?size=300x300&margin=4&data='.rawurlencode($verify);
$data=['organization'=>$r['organization_name'],'tour'=>$r['tour_name'],'dates'=>trim((string)$r['start_date']).($r['end_date']?' — '.(string)$r['end_date']:''),'guest'=>$r['full_name'],'phone'=>$r['phone'],'bus'=>$seat['bus_name']??'Not assigned','bus_number'=>$seat['bus_number']??'—','seat'=>$seat['seat_code']??'Not assigned','room'=>$room?trim((string)$room['room_no'].' · '.(string)$room['room_type']):'Not assigned','paid'=>number_format($paid,2),'due'=>$due<=0?'PAID':$cur.' '.number_format($due,2),'ticket'=>$r['ticket_number'],'currency'=>$cur];
?>
<article class="ticket" style="background:#fff">
<?php if($elements): ?><div class="artwork" style="background-image:url('<?=saas_h((string)($design['background_image']??''))?>')"></div>
<?php foreach($elements as $key=>$v): if($key==='qr'): ?><div class="el qr" style="left:<?=$v['x']?>px;top:<?=$v['y']?>px;width:<?=$v['w']?>px;height:<?=$v['h']?>px"><img src="<?=saas_h($qr)?>" alt="QR"></div>
<?php elseif(array_key_exists($key,$data)): ?><div class="el" style="left:<?=$v['x']?>px;top:<?=$v['y']?>px;width:<?=$v['w']?>px;height:<?=$v['h']?>px;font-size:<?=$v['size']?>px;font-weight:<?=$v['weight']?>"><?=saas_h((string)$data[$key])?></div>
<?php endif;endforeach; else: ?>
<div class="fallback-title"><?=saas_h($data['tour'])?></div><div class="fallback-guest"><?=saas_h($data['guest'])?></div><div class="fallback-info">Bus: <?=saas_h($data['bus'])?> · Seat: <?=saas_h($data['seat'])?> · Room: <?=saas_h($data['room'])?> · <?=saas_h($data['ticket'])?></div><img class="fallback-qr" src="<?=saas_h($qr)?>" alt="QR">
<?php endif; ?></article>
<?php endforeach; ?></section><?php endforeach; ?></body></html>