<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
saas_require_login();$orgId=saas_require_organization();$tourId=saas_require_tour();saas_require_permission('tour.edit');$db=saas_db();$tour=saas_current_tour();
$error='';$saved=false;
$defaults=[
 'organization'=>['x'=>28,'y'=>20,'w'=>300,'h'=>28,'label'=>'Organization','size'=>15,'weight'=>700],
 'tour'=>['x'=>28,'y'=>52,'w'=>430,'h'=>42,'label'=>'Tour Name','size'=>27,'weight'=>800],
 'dates'=>['x'=>28,'y'=>100,'w'=>330,'h'=>25,'label'=>'Dates','size'=>13,'weight'=>600],
 'guest'=>['x'=>28,'y'=>145,'w'=>420,'h'=>34,'label'=>'Passenger Name','size'=>22,'weight'=>800],
 'phone'=>['x'=>28,'y'=>184,'w'=>260,'h'=>24,'label'=>'Phone','size'=>12,'weight'=>500],
 'bus'=>['x'=>28,'y'=>218,'w'=>210,'h'=>38,'label'=>'Bus','size'=>14,'weight'=>700],
 'bus_number'=>['x'=>246,'y'=>218,'w'=>145,'h'=>38,'label'=>'Bus No.','size'=>14,'weight'=>700],
 'seat'=>['x'=>28,'y'=>263,'w'=>145,'h'=>38,'label'=>'Seat','size'=>14,'weight'=>700],
 'room'=>['x'=>181,'y'=>263,'w'=>210,'h'=>38,'label'=>'Room','size'=>14,'weight'=>700],
 'paid'=>['x'=>28,'y'=>307,'w'=>145,'h'=>32,'label'=>'Paid','size'=>12,'weight'=>700],
 'due'=>['x'=>181,'y'=>307,'w'=>170,'h'=>32,'label'=>'Due','size'=>12,'weight'=>700],
 'ticket'=>['x'=>28,'y'=>343,'w'=>240,'h'=>22,'label'=>'Ticket No.','size'=>10,'weight'=>700],
 'qr'=>['x'=>525,'y'=>100,'w'=>165,'h'=>165,'label'=>'QR Code','size'=>10,'weight'=>700],
];
$q=$db->prepare('SELECT * FROM tour_ticket_designs WHERE tour_id=? AND organization_id=? LIMIT 1');$q->execute([$tourId,$orgId]);$design=$q->fetch();
$elements=$design?json_decode((string)$design['elements_json'],true):$defaults;if(!is_array($elements))$elements=$defaults;if($design && ((int)($design['canvas_width']??0)!==720 || (int)($design['canvas_height']??0)!==350)){foreach($elements as &$ev){$ev['x']=round(((int)($ev['x']??0))*720/max(1,(int)($design['canvas_width']??1120)));$ev['y']=round(((int)($ev['y']??0))*350/max(1,(int)($design['canvas_height']??448)));$ev['w']=max(1,round(((int)($ev['w']??1))*720/max(1,(int)($design['canvas_width']??1120))));$ev['h']=max(1,round(((int)($ev['h']??1))*350/max(1,(int)($design['canvas_height']??448)));$ev['size']=max(1,round(((int)($ev['size']??12))*0.78));}unset($ev);}
$background=(string)($design['background_image']??'');$name=(string)($design['design_name']??'Default');
function design_upload(string $field,int $tourId): string{
 if(empty($_FILES[$field])||($_FILES[$field]['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return '';
 $f=$_FILES[$field];if((int)$f['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Could not upload the design image.');
 if((int)$f['size']>10*1024*1024)throw new RuntimeException('Design image must be 10 MB or smaller.');
 $info=@getimagesize((string)$f['tmp_name']);if(!$info)throw new RuntimeException('Invalid design image.');
 $mime=(string)($info['mime']??'');$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allowed[$mime]))throw new RuntimeException('Design must be JPG, PNG or WebP.');
 $dir=__DIR__.'/uploads/tours/'.$tourId.'/ticket-design';if(!is_dir($dir)&&!@mkdir($dir,0775,true)&&!is_dir($dir))throw new RuntimeException('Could not create ticket design directory.');
 if(!is_writable($dir))throw new RuntimeException('Ticket design directory is not writable.');
 $file='background-'.bin2hex(random_bytes(8)).'.'.$allowed[$mime];if(!move_uploaded_file((string)$f['tmp_name'],$dir.'/'.$file))throw new RuntimeException('Could not save the design image.');
 return '/uploads/tours/'.$tourId.'/ticket-design/'.$file;
}
if($_SERVER['REQUEST_METHOD']==='POST'){try{saas_check_csrf();$posted=json_decode((string)($_POST['elements_json']??''),true);if(!is_array($posted))throw new RuntimeException('Invalid design layout.');foreach($posted as $k=>$v){if(!isset($defaults[$k]))unset($posted[$k]);else foreach(['x','y','w','h','size','weight'] as $n)$posted[$k][$n]=max(1,min(1200,(int)($posted[$k][$n]??$defaults[$k][$n])));}$elements=$posted;$newBg=design_upload('background',$tourId);if($newBg!=='')$background=$newBg;$name=trim((string)($_POST['design_name']??'Default'))?:'Default';$q=$db->prepare('INSERT INTO tour_ticket_designs(tour_id,organization_id,design_name,canvas_width,canvas_height,background_image,elements_json,created_by) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE design_name=VALUES(design_name),background_image=VALUES(background_image),elements_json=VALUES(elements_json),updated_at=NOW()');$q->execute([$tourId,$orgId,$name,720,350,$background?:null,json_encode($elements,JSON_UNESCAPED_UNICODE),saas_user_id()]);$saved=true;}catch(Throwable $e){$error=$e->getMessage();}}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ticket Designer — GoTM</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6fa;color:#172033;font-family:Inter,Arial,sans-serif}.top{padding:16px 22px;background:#fff;border-bottom:1px solid #e5e7eb;display:flex;align-items:center;justify-content:space-between;gap:15px;position:sticky;top:0;z-index:20}.top h1{margin:0;font-size:20px}.muted{color:#667085;font-size:12px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid #d0d5dd;background:#fff;color:#172033;padding:9px 13px;border-radius:9px;font-weight:800;text-decoration:none;cursor:pointer}.primary{background:#155eef;color:#fff;border-color:#155eef}.layout{display:grid;grid-template-columns:260px 1fr;min-height:calc(100vh - 70px)}.panel{background:#fff;border-right:1px solid #e5e7eb;padding:18px;overflow:auto}.panel h3{font-size:13px;margin:0 0 10px}.field{margin-bottom:10px}.field label{display:block;font-size:11px;font-weight:800;margin-bottom:5px}.field input{width:100%;padding:9px;border:1px solid #d0d5dd;border-radius:8px}.element{padding:10px;border:1px solid #e4e7ec;border-radius:9px;margin:6px 0;background:#f8fafc;cursor:grab;font-weight:700;font-size:12px}.stage-wrap{overflow:auto;padding:35px}.stage{width:720px;height:350px;position:relative;background:#fff center/100% 100% no-repeat;box-shadow:0 15px 45px #10182820;margin:auto}.stage:after{content:'';position:absolute;inset:0;border:1px dashed #94a3b8;pointer-events:none}.item{position:absolute;border:1px dashed #155eef88;background:#ffffffb8;cursor:move;padding:4px 7px;overflow:hidden;white-space:nowrap;user-select:none}.item.selected{outline:2px solid #155eef}.item.qr{background:#fff;padding:0}.item.qr:before{content:'QR CODE';display:flex;align-items:center;justify-content:center;height:100%;font-size:12px;color:#667085}.help{font-size:11px;line-height:1.5;color:#667085;background:#f8fafc;padding:10px;border-radius:9px;margin-top:12px}.alert{padding:10px;margin:12px 20px;border-radius:9px}.ok{background:#ecfdf3;color:#067647}.err{background:#fef3f2;color:#b42318}@media(max-width:900px){.layout{grid-template-columns:1fr}.panel{border-right:0;border-bottom:1px solid #e5e7eb}.stage-wrap{padding:15px}}
</style></head><body>
<header class="top"><div><h1>Ticket Visual Designer</h1><div class="muted"><?=saas_h($tour['name'])?> · Canvas 720 × 350 px · A4 portrait · 3 tickets per sheet</div></div><div class="actions"><a class="btn" href="tickets.php">Back to Tickets</a><button class="btn primary" id="saveBtn" type="button">Save Design</button></div></header>
<?php if($saved):?><div class="alert ok">Design saved. All tickets now use these positions dynamically.</div><?php endif;?><?php if($error):?><div class="alert err"><?=saas_h($error)?></div><?php endif;?>
<form id="designForm" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=saas_h(saas_csrf())?>"><input type="hidden" name="elements_json" id="elementsJson"><div class="layout"><aside class="panel"><h3>Design settings</h3><div class="field"><label>Design name</label><input name="design_name" value="<?=saas_h($name)?>"></div><div class="field"><label>Background / ticket artwork</label><input type="file" name="background" accept="image/jpeg,image/png,image/webp"></div><div class="muted">Recommended artwork: 720 × 350 px. A4 portrait, 3 tickets per sheet with cutting gap. JPG/PNG/WebP, max 10 MB. JPG/PNG/WebP, max 10 MB.</div><hr><h3>Drag elements on canvas</h3><div id="elements"></div><div class="help">Drag any field to position it. Drag the blue corner/edge conceptually by changing Width/Height in the selected field controls. Save once; every issued ticket will fill these fields with live passenger data.</div></aside><main class="stage-wrap"><div class="stage" id="stage" style="background-image:url('<?=saas_h($background)?>')"></div></main></div></form>
<script>
const defs=<?=json_encode($defaults,JSON_UNESCAPED_UNICODE)?>;let state=<?=json_encode($elements,JSON_UNESCAPED_UNICODE)?>;const labels=Object.fromEntries(Object.entries(defs).map(([k,v])=>[k,v.label]));let selected=null;
const stage=document.getElementById('stage'), list=document.getElementById('elements');
function render(){stage.querySelectorAll('.item').forEach(e=>e.remove());list.innerHTML='';Object.entries(state).forEach(([key,v])=>{const el=document.createElement('div');el.className='item'+(key==='qr'?' qr':'');el.dataset.key=key;el.textContent=key==='qr'?'':labels[key];el.style.left=v.x+'px';el.style.top=v.y+'px';el.style.width=v.w+'px';el.style.height=v.h+'px';el.style.fontSize=v.size+'px';el.style.fontWeight=v.weight;stage.appendChild(el);const row=document.createElement('div');row.className='element';row.textContent=labels[key];row.onclick=()=>select(key);list.appendChild(row);el.onmousedown=e=>drag(e,key);});}
function select(k){selected=k;stage.querySelectorAll('.item').forEach(e=>e.classList.toggle('selected',e.dataset.key===k));}
function drag(e,key){e.preventDefault();select(key);const startX=e.clientX,startY=e.clientY,ox=state[key].x,oy=state[key].y;function move(ev){state[key].x=Math.max(0,Math.min(720-state[key].w,Math.round(ox+ev.clientX-startX)));state[key].y=Math.max(0,Math.min(350-state[key].h,Math.round(oy+ev.clientY-startY)));render();select(key)}function up(){document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up)}document.addEventListener('mousemove',move);document.addEventListener('mouseup',up)}
document.getElementById('saveBtn').onclick=()=>{document.getElementById('elementsJson').value=JSON.stringify(state);document.getElementById('designForm').submit()};render();
</script></body></html>