<?php require __DIR__.'/bootstrap.php';require __DIR__.'/bootstrap_auth.php';require_login();
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$action=$_POST['action']??'';try{
 if($action==='add'){require_permission('tour.create'); require_permission('tour.create'); $q=db()->prepare("INSERT INTO tours(name,start_date,end_date,default_fee,booking_fee,status) VALUES(?,?,?,?,?,'ACTIVE')");$q->execute([trim($_POST['name']),$_POST['start_date']?:null,$_POST['end_date']?:null,(float)$_POST['default_fee'],(float)$_POST['booking_fee']]);$id=(int)db()->lastInsertId();$_SESSION['tour_id']=$id;audit('ADD_TOUR','tour',$id,$_POST['name']);flash('success','New tour created.');}
 elseif($action==='edit'){ require_permission('tour.edit'); $id=(int)$_POST['id'];$q=db()->prepare("UPDATE tours SET name=?,start_date=?,end_date=?,default_fee=?,booking_fee=?,status=? WHERE id=?");$q->execute([trim($_POST['name']),$_POST['start_date']?:null,$_POST['end_date']?:null,(float)$_POST['default_fee'],(float)$_POST['booking_fee'],$_POST['status'],$id]);audit('UPDATE_TOUR','tour',$id,$_POST['name']);flash('success','Tour updated.');}
 elseif($action==='delete'){require_permission('tour.delete'); require_permission('tour.delete'); $id=(int)$_POST['id'];$count=db()->prepare("SELECT COUNT(*) FROM passengers WHERE tour_id=?");$count->execute([$id]);if((int)$count->fetchColumn()>0)throw new Exception('Cannot delete a tour that already has passengers. Set it to Archived instead.');db()->prepare("DELETE FROM tours WHERE id=?")->execute([$id]);if(current_tour_id()===$id)unset($_SESSION['tour_id']);audit('DELETE_TOUR','tour',$id);flash('success','Tour deleted.');}
}catch(Throwable $e){flash('danger',$e->getMessage());}redirect('tour_manage.php');}
$rows=tours();
?><!doctype html><html><head><?php include __DIR__.'/partials/head.php';?></head><body><?php include __DIR__.'/partials/nav.php';?><main class="wrap"><?php flash_render();?><?php if(can("tour.create")):?><section class="card"><div class="head"><div><div class="eyebrow">TOUR MANAGEMENT</div><h2>New Tour</h2></div></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="add"><div class="formgrid"><label>Tour Name<input name="name" required></label><label>Start Date<input type="date" name="start_date"></label><label>End Date<input type="date" name="end_date"></label><label>Default Fee<input type="number" name="default_fee" value="4000" min="0"></label><label>Default Booking Fee<input type="number" name="booking_fee" value="2000" min="0"></label></div><button class="btn primary">+ Create New Tour</button></form></section><?php endif;?>
<section class="card"><h2>All Tours</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Dates</th><th>Fee</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=h($r['name'])?></b></td><td><?=h($r['start_date'])?> → <?=h($r['end_date'])?></td><td><?=money($r['default_fee'])?></td><td><span class="badge"><?=h($r['status'])?></span></td><td><a class="btn primary" href="tour_edit.php?id=<?=$r['id']?>">Edit</a> <?php if(can("tour.delete")):?><form method="post" style="display:inline" onsubmit="return confirm('Delete this empty tour?')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><?php if(can("tour.delete")):?><button class="btn danger">Delete</button><?php endif;?></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
