-- Bus layout compatibility migration.
-- The canonical foundation already creates the supported layouts and the
-- unique physical-seat constraint, so this migration is intentionally a
-- no-op on a fresh installation. It remains as a tracked version for
-- compatibility with earlier migration histories.
