-- Secure ticket identity and QR verification.
CREATE TABLE ticket_instances (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 tour_passenger_id BIGINT UNSIGNED NOT NULL,
 organization_id BIGINT UNSIGNED NOT NULL,
 tour_id BIGINT UNSIGNED NOT NULL,
 ticket_number VARCHAR(40) NOT NULL,
 qr_token_hash CHAR(64) NOT NULL,
 qr_token_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 qr_token_revoked_at DATETIME NULL,
 status ENUM('ISSUED','VOID','USED') NOT NULL DEFAULT 'ISSUED',
 issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 voided_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),
 UNIQUE KEY uq_ticket_number(ticket_number),
 UNIQUE KEY uq_ticket_passenger(tour_passenger_id),
 UNIQUE KEY uq_ticket_qr_hash(qr_token_hash),
 KEY idx_ticket_org_tour(organization_id,tour_id),
 KEY idx_ticket_qr(qr_token_hash),
 CONSTRAINT fk_ticket_tp FOREIGN KEY(tour_passenger_id) REFERENCES tour_passengers(id) ON DELETE CASCADE,
 CONSTRAINT fk_ticket_org FOREIGN KEY(organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
 CONSTRAINT fk_ticket_tour FOREIGN KEY(tour_id) REFERENCES tours(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
